//! Bundled ERC-20 token logo SVGs, sourced from the Optimism tokenlist
//! (<https://static.optimism.io/optimism.tokenlist.json>) and synced into
//! `assets/<chain>/<address>/logo.svg` by `cargo xtask sync-tokens`. The
//! workspace `build.rs` walks that tree at compile time and embeds every
//! logo via `include_bytes!`, so Kao ships as a single static binary and
//! never has to fetch logos at runtime — fetching would leak the user's
//! holdings to whichever CDN served them, which would be at odds with
//! the privacy posture of the Helios-backed RPC layer.
//!
//! Tokens not in the bundled set fall back to the kaomoji avatar in
//! `kao_widgets::token_avatar`, which is a deliberate part of the
//! wallet's identity rather than a placeholder.

use std::collections::HashMap;
use std::sync::LazyLock;

use alloy::primitives::Address;
use iced::widget::svg::Handle;

use crate::chain::Chain;

// Generated by `build.rs`. Each tuple is
// (chain dir name, lowercase hex address, svg bytes).
static LOGOS: &[(&str, &str, &[u8])] = include!(concat!(env!("OUT_DIR"), "/logos.rs"));

static MAP: LazyLock<HashMap<(Chain, Address), Handle>> = LazyLock::new(|| {
    LOGOS
        .iter()
        .filter_map(|(chain, addr, bytes)| {
            let chain = match *chain {
                "ethereum" => Chain::Mainnet,
                "optimism" => Chain::Optimism,
                "base" => Chain::Base,
                _ => return None,
            };
            let addr: Address = addr.parse().ok()?;
            Some(((chain, addr), Handle::from_memory(*bytes)))
        })
        .collect()
});

/// Resolve the bundled SVG for `(chain, contract)`. `contract = None`
/// means native ETH; the icon is identical on every chain so all native
/// lookups resolve via the mainnet `0x0000…` entry. Returns `None` when
/// no SVG is bundled for the address — caller falls back to the kaomoji
/// avatar.
pub fn handle(chain: Chain, contract: Option<Address>) -> Option<Handle> {
    let key = match contract {
        None => (Chain::Mainnet, Address::ZERO),
        Some(addr) => (chain, addr),
    };
    MAP.get(&key).cloned()
}
