//! Name-service app — a search-first surface for registering and managing names
//! across ENS (`.eth`), GNS (`.gwei`), WNS (`.wei`) and XNS (`.xns`, `.crops`
//! and any permissionless namespace), surfaced as a tile in the Apps launcher.
//!
//! This pane is a self-contained Elm widget: it owns ephemeral UI state and emits
//! [`Outcome`]s for the coordinator to turn into verified reads / signed
//! transactions, and never touches the network itself.
//!
//! - **Home** — one big search bar. Empty, it lists the names that resolve to the
//!   active account (reverse-lookup discovery, plus manual add). Typed, it checks
//!   the label across every namespace and filters your own names by it.
//! - **Register** — a focused panel for one name: the two-step commit → wait 60s
//!   → reveal flow for the commit-reveal registrars, or XNS's single transaction.
//! - **Manage** — renew / re-point an owned commit-reveal name (XNS names are
//!   permanent + immutable, so they have nothing to manage).
//!
//! The commit/reveal `secret` is generated by the coordinator (which owns the
//! RNG), handed back inside the [`RegisterPlan`] on a successful commit, and
//! replayed verbatim on the reveal — so the two transactions agree by
//! construction.

use std::time::Duration;

use alloy::primitives::{Address, TxHash, U256};
use iced::border::Radius;
use iced::widget::{Space, button, column, container, row, text, text_input};
use iced::{Alignment, Background, Border, Color, Element, Length, Padding, Subscription};

use crate::names::manage::{HitStatus, NameState, NameStatus, Query, Registry, SearchHit};
use crate::names::registrar::{self, Namespace, RegisterPlan};
use crate::ui::kao_theme::{KaoTheme, with_alpha};
use crate::ui::kao_widgets::{
    bold, colored_address, ghost_button, mono, primary_button, screen_subtitle, screen_title,
    secondary_button, small_secondary_button, text_input_style,
};

/// ENS registration term bounds (years). GNS/WNS grant a fixed 365-day term and
/// XNS names are permanent; both ignore this.
const MIN_YEARS: u32 = 1;
const MAX_YEARS: u32 = 10;

// Kaomoji palette for the surface.
const KAO_MASCOT: &str = "(๑>؂•̀๑)";
const KAO_AVAILABLE: &str = "(๑ᵔ⤙ᵔ๑)";
const KAO_TAKEN: &str = "(*ᴗ͈ˬᴗ͈)ꕤ*.ﾟ";

#[derive(Debug, Clone)]
pub enum Message {
    // ── search ──
    QueryChanged(String),
    Search,
    Refresh,
    // ── owned: manual add ──
    AddInputChanged(String),
    AddName,
    OpenManage(usize),
    // ── navigation ──
    Back,
    // ── register panel ──
    PickResult(usize),
    YearsDec,
    YearsInc,
    StartRegister,
    CompleteRegister,
    ResetRegister,
    // ── manage ──
    RenewYearsDec,
    RenewYearsInc,
    Renew,
    ManageRecipientChanged(String),
    SetRecipient,
    // ── timer for the commit→reveal wait ──
    Tick,
}

/// Requests the pane bubbles up to the coordinator.
#[derive(Debug, Clone)]
pub enum Outcome {
    /// Discover names that resolve to the active account (reverse lookup).
    ReverseScan,
    /// Check `label` across `registries` (availability + price).
    Search {
        label: String,
        registries: Vec<Registry>,
    },
    /// Verify one manually-entered name's status (for manual add).
    Status { registry: Registry, label: String },
    /// Commit-reveal step 1 (ENS/GNS/WNS). The name is always registered to the
    /// signing account (`reveal` mints to `msg.sender`); a different recipient is
    /// set afterward.
    Commit {
        namespace: Namespace,
        label: String,
        years: u32,
    },
    /// Commit-reveal step 2: broadcast the reveal/register for the committed plan.
    Register { plan: RegisterPlan },
    /// XNS one-shot registration. The name is bound to (and resolves to) the
    /// signing account, immutably.
    RegisterXns { namespace: String, label: String },
    /// Renew ("prolong") an owned commit-reveal name.
    Renew {
        namespace: Namespace,
        label: String,
        years: u32,
    },
    /// Point an owned commit-reveal name at `recipient`.
    SetRecipient {
        namespace: Namespace,
        label: String,
        recipient: Address,
    },
}

/// Which sub-view is showing.
#[derive(Debug, Clone, PartialEq, Eq)]
enum View {
    Home,
    Register,
    Manage(usize),
}

/// The registration flow's state machine. XNS skips `Committing`/`Waiting`.
#[derive(Debug, Clone)]
enum RegPhase {
    /// Picked from search; price quoted, ready to start.
    Ready {
        quote: Option<crate::names::manage::RegisterQuote>,
    },
    /// Commit broadcast in flight (commit-reveal only).
    Committing,
    /// Commit mined; counting down `MIN_COMMITMENT_AGE` before the reveal.
    Waiting { plan: RegisterPlan, since: u64 },
    /// Reveal/register broadcast in flight.
    Registering,
    /// Registered.
    Done,
    /// A step failed.
    Failed(String),
}

/// The focused registration panel's target + state.
#[derive(Debug, Clone)]
struct RegisterFlow {
    registry: Registry,
    label: String,
    full: String,
    years: u32,
    phase: RegPhase,
}

#[derive(Debug)]
pub struct NamesApp {
    owner: Address,
    view: View,
    /// Whether the initial reverse scan has been kicked off yet.
    loaded: bool,

    // Search
    query: String,
    searching: bool,
    /// The bare label the current `results` are for (drives "yours" filtering).
    result_label: Option<String>,
    results: Vec<SearchHit>,

    // Owned (reverse lookup + manual add)
    owned: Vec<NameStatus>,
    scanning: bool,
    notice: Option<(bool, String)>,
    add_input: String,
    adding: bool,

    // Register panel
    reg: Option<RegisterFlow>,

    // Manage panel
    manage_years: u32,
    manage_recipient: String,
    manage_busy: bool,
    manage_notice: Option<(bool, String)>,
}

impl NamesApp {
    pub fn new(owner: Address) -> Self {
        Self {
            owner,
            view: View::Home,
            loaded: false,
            query: String::new(),
            searching: false,
            result_label: None,
            results: Vec::new(),
            owned: Vec::new(),
            scanning: false,
            notice: None,
            add_input: String::new(),
            adding: false,
            reg: None,
            manage_years: 1,
            manage_recipient: String::new(),
            manage_busy: false,
            manage_notice: None,
        }
    }

    /// Called when the app is opened from the launcher — kicks off the reverse
    /// scan once so "your names" populates without a manual tap.
    pub fn on_open(&mut self) -> Option<Outcome> {
        if self.loaded {
            return None;
        }
        self.loaded = true;
        self.scanning = true;
        Some(Outcome::ReverseScan)
    }

    /// A 1-second tick drives the commit→reveal countdown; only subscribed while
    /// the register flow is in a time-sensitive phase.
    pub fn subscription(&self) -> Subscription<Message> {
        let active = matches!(
            self.reg.as_ref().map(|r| &r.phase),
            Some(RegPhase::Committing | RegPhase::Waiting { .. } | RegPhase::Registering)
        );
        if active {
            iced::time::every(Duration::from_secs(1)).map(|_| Message::Tick)
        } else {
            Subscription::none()
        }
    }

    pub fn update(&mut self, msg: Message) -> Option<Outcome> {
        match msg {
            Message::Tick => None,

            // ── search ──
            Message::QueryChanged(s) => {
                self.query = s;
                None
            }
            Message::Search => self.run_search(),
            Message::Refresh => {
                if self.scanning {
                    return None;
                }
                self.scanning = true;
                self.notice = None;
                Some(Outcome::ReverseScan)
            }

            // ── owned: manual add ──
            Message::AddInputChanged(s) => {
                self.add_input = s;
                None
            }
            Message::AddName => {
                if self.adding {
                    return None;
                }
                match crate::names::manage::parse_one_name(&self.add_input) {
                    Ok((registry, label)) => {
                        self.adding = true;
                        self.notice = None;
                        Some(Outcome::Status { registry, label })
                    }
                    Err(e) => {
                        self.notice = Some((true, e));
                        None
                    }
                }
            }
            Message::OpenManage(idx) => {
                if let Some(n) = self.owned.get(idx)
                    && n.registry.supports_renew()
                {
                    self.manage_years = 1;
                    self.manage_recipient = String::new();
                    self.manage_busy = false;
                    self.manage_notice = None;
                    self.view = View::Manage(idx);
                }
                None
            }

            // ── nav ──
            Message::Back => {
                self.view = View::Home;
                self.reg = None;
                None
            }

            // ── register panel ──
            Message::PickResult(idx) => {
                if let Some(hit) = self.results.get(idx)
                    && let HitStatus::Available { quote } = &hit.status
                {
                    self.reg = Some(RegisterFlow {
                        registry: hit.registry.clone(),
                        label: hit.label.clone(),
                        full: hit.full.clone(),
                        years: 1,
                        phase: RegPhase::Ready { quote: *quote },
                    });
                    self.view = View::Register;
                }
                None
            }
            Message::YearsDec => {
                if let Some(r) = &mut self.reg {
                    r.years = r.years.saturating_sub(1).max(MIN_YEARS);
                }
                None
            }
            Message::YearsInc => {
                if let Some(r) = &mut self.reg {
                    r.years = (r.years + 1).min(MAX_YEARS);
                }
                None
            }
            Message::StartRegister => self.start_register(),
            Message::CompleteRegister => self.complete_register(),
            Message::ResetRegister => {
                self.view = View::Home;
                self.reg = None;
                None
            }

            // ── manage ──
            Message::RenewYearsDec => {
                self.manage_years = self.manage_years.saturating_sub(1).max(MIN_YEARS);
                None
            }
            Message::RenewYearsInc => {
                self.manage_years = (self.manage_years + 1).min(MAX_YEARS);
                None
            }
            Message::Renew => {
                let View::Manage(idx) = self.view else {
                    return None;
                };
                let n = self.owned.get(idx)?;
                let ns = n.registry.legacy()?;
                if self.manage_busy {
                    return None;
                }
                self.manage_busy = true;
                self.manage_notice = None;
                Some(Outcome::Renew {
                    namespace: ns,
                    label: n.label.clone(),
                    years: self.manage_years,
                })
            }
            Message::ManageRecipientChanged(s) => {
                self.manage_recipient = s;
                None
            }
            Message::SetRecipient => {
                let View::Manage(idx) = self.view else {
                    return None;
                };
                let n = self.owned.get(idx)?;
                let ns = n.registry.legacy()?;
                if self.manage_busy {
                    return None;
                }
                let recipient = match self.manage_recipient.trim().parse::<Address>() {
                    Ok(a) => a,
                    Err(_) => {
                        self.manage_notice = Some((true, "enter a valid 0x… address".to_string()));
                        return None;
                    }
                };
                self.manage_busy = true;
                self.manage_notice = None;
                Some(Outcome::SetRecipient {
                    namespace: ns,
                    label: n.label.clone(),
                    recipient,
                })
            }
        }
    }

    /// Parse the search bar and emit the cross-namespace check.
    fn run_search(&mut self) -> Option<Outcome> {
        match crate::names::manage::parse_query(&self.query) {
            Ok(Query::Bare(label)) => {
                self.searching = true;
                self.notice = None;
                self.result_label = Some(label.clone());
                Some(Outcome::Search {
                    label,
                    registries: Registry::defaults(),
                })
            }
            Ok(Query::One { registry, label }) => {
                self.searching = true;
                self.notice = None;
                self.result_label = Some(label.clone());
                Some(Outcome::Search {
                    label,
                    registries: vec![registry],
                })
            }
            Err(e) => {
                self.notice = Some((true, e));
                None
            }
        }
    }

    /// Begin registration for the focused name — commit (legacy) or one-shot
    /// register (XNS).
    fn start_register(&mut self) -> Option<Outcome> {
        let r = self.reg.as_mut()?;
        if !matches!(r.phase, RegPhase::Ready { .. } | RegPhase::Failed(_)) {
            return None;
        }
        match r.registry.legacy() {
            Some(ns) => {
                r.phase = RegPhase::Committing;
                Some(Outcome::Commit {
                    namespace: ns,
                    label: r.label.clone(),
                    years: r.years,
                })
            }
            None => {
                let namespace = r.registry.xns_namespace()?.to_string();
                r.phase = RegPhase::Registering;
                Some(Outcome::RegisterXns {
                    namespace,
                    label: r.label.clone(),
                })
            }
        }
    }

    /// Finish the commit-reveal flow (step 2). Guards both the 60s minimum and
    /// the 24h maximum so a late click doesn't broadcast an expired commitment.
    fn complete_register(&mut self) -> Option<Outcome> {
        let r = self.reg.as_mut()?;
        let RegPhase::Waiting { plan, since } = &r.phase else {
            return None;
        };
        let elapsed = crate::names::manage::now_secs().saturating_sub(*since);
        if elapsed < registrar::MIN_COMMITMENT_AGE {
            return None;
        }
        if elapsed > registrar::MAX_COMMITMENT_AGE {
            r.phase =
                RegPhase::Failed("commitment expired (waited over 24h) — start over".to_string());
            return None;
        }
        let plan = plan.clone();
        r.phase = RegPhase::Registering;
        Some(Outcome::Register { plan })
    }

    // ── result callbacks (coordinator → pane) ─────────────────────────────────

    pub fn on_reverse_scan(&mut self, result: Result<Vec<NameStatus>, String>) {
        self.scanning = false;
        match result {
            Ok(found) => {
                let n = found.len();
                self.merge_owned(found);
                self.notice = Some((
                    false,
                    if self.owned.is_empty() {
                        "No names point to this account yet.".to_string()
                    } else {
                        format!("{n} name(s) resolve to you.")
                    },
                ));
            }
            Err(e) => self.notice = Some((true, format!("Scan failed: {e}"))),
        }
    }

    pub fn on_search(&mut self, result: Result<Vec<SearchHit>, String>) {
        self.searching = false;
        match result {
            Ok(hits) => self.results = hits,
            Err(e) => {
                self.results.clear();
                self.notice = Some((true, e));
            }
        }
    }

    pub fn on_status(&mut self, result: Result<NameStatus, String>) {
        self.adding = false;
        match result {
            Ok(status) => {
                if status.owned_by(self.owner) && status.state() != NameState::Unregistered {
                    self.add_input.clear();
                    let full = status.full.clone();
                    self.merge_owned(vec![status]);
                    self.notice = Some((false, format!("Added {full}.")));
                } else {
                    self.notice = Some((true, "that name isn't held by this account".to_string()));
                }
            }
            Err(e) => self.notice = Some((true, e)),
        }
    }

    pub fn on_commit(&mut self, result: Result<(RegisterPlan, TxHash), String>) {
        let Some(r) = &mut self.reg else { return };
        match result {
            Ok((plan, _hash)) => {
                r.phase = RegPhase::Waiting {
                    plan,
                    since: crate::names::manage::now_secs(),
                };
            }
            Err(e) => r.phase = RegPhase::Failed(e),
        }
    }

    pub fn on_register(&mut self, result: Result<(String, TxHash), String>) {
        let Some(r) = &mut self.reg else { return };
        match result {
            Ok(_) => r.phase = RegPhase::Done,
            Err(e) => r.phase = RegPhase::Failed(e),
        }
    }

    pub fn on_renew(&mut self, result: Result<(String, TxHash), String>) {
        self.manage_busy = false;
        match result {
            Ok((name, _)) => self.manage_notice = Some((false, format!("Renewed {name}."))),
            Err(e) => self.manage_notice = Some((true, e)),
        }
    }

    pub fn on_set_recipient(&mut self, result: Result<(String, TxHash), String>) {
        self.manage_busy = false;
        match result {
            Ok((name, _)) => {
                self.manage_recipient.clear();
                self.manage_notice = Some((false, format!("Updated {name}'s recipient.")));
            }
            Err(e) => self.manage_notice = Some((true, e)),
        }
    }

    /// Upsert by (registry, label) so a re-scan or manual re-add refreshes a row
    /// rather than duplicating it.
    fn merge_owned(&mut self, incoming: Vec<NameStatus>) {
        for n in incoming {
            if let Some(existing) = self
                .owned
                .iter_mut()
                .find(|e| e.registry == n.registry && e.label == n.label)
            {
                *existing = n;
            } else {
                self.owned.push(n);
            }
        }
        self.owned.sort_by(|a, b| {
            a.full
                .cmp(&b.full)
                .then(a.registry.badge().cmp(b.registry.badge()))
        });
    }

    /// Whether the active account owns `label` in `registry` (cross-reference for
    /// "you own this" on a search row whose `Taken` carries no owner).
    fn owns(&self, registry: &Registry, label: &str) -> bool {
        self.owned
            .iter()
            .any(|n| &n.registry == registry && n.label == label)
    }

    // ── views ─────────────────────────────────────────────────────────────────

    pub fn view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        match &self.view {
            View::Home => self.home_view(t),
            View::Register => self.register_view(t),
            View::Manage(idx) => self.manage_view(t, *idx),
        }
    }

    fn home_view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        let header = row![
            column![
                screen_title(t, "Names"),
                Space::new().height(4),
                screen_subtitle(t, "Search & register across .eth / .gwei / .wei / .xns"),
            ]
            .width(Length::Fill),
            text(KAO_MASCOT).size(22).color(t.a3).font(bold()),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill);

        // The big search bar — primary interaction. The input fills; the action
        // is a compact pill so the bar gets the room.
        let search = row![
            text_input(
                "search a name — kitty, vitalik.eth, cow.crops…",
                &self.query
            )
            .on_input(Message::QueryChanged)
            .on_submit(Message::Search)
            .padding(Padding::from([14, 18]))
            .size(16)
            .width(Length::Fill)
            .style(move |_, s| text_input_style(t, s)),
            Space::new().width(10),
            pill_button(
                t,
                if self.searching { "…" } else { "Search" },
                Message::Search
            ),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill);

        let mut body = column![
            header,
            Space::new().height(16),
            search,
            Space::new().height(10)
        ]
        .width(Length::Fill)
        .max_width(640);

        if let Some((is_err, msg)) = &self.notice {
            body =
                body.push(
                    text(msg.clone())
                        .size(12)
                        .color(if *is_err { t.down } else { t.sub }),
                );
            body = body.push(Space::new().height(8));
        }

        let has_query = self.result_label.is_some() && !self.query.trim().is_empty();

        // ── "Your names" — reverse-discovered + manually added, filtered by the
        //    active query so the search bar searches over them too.
        let filter = self
            .result_label
            .as_deref()
            .filter(|_| has_query)
            .map(str::to_ascii_lowercase);
        let owned_rows: Vec<&NameStatus> = self
            .owned
            .iter()
            .filter(|n| match &filter {
                Some(q) => n.full.to_ascii_lowercase().contains(q) || n.label.contains(q),
                None => true,
            })
            .collect();

        body = body.push(section_label(t, "YOUR NAMES"));
        body = body.push(Space::new().height(8));
        if owned_rows.is_empty() {
            let msg = if self.scanning {
                "Looking up names that point to you…"
            } else if has_query {
                "None of your names match that."
            } else {
                "No names point to this account yet. Register one below, or add one you own."
            };
            body = body.push(empty_hint(t, msg));
        } else {
            let mut list = column![].spacing(8).width(Length::Fill);
            for n in &owned_rows {
                // Map the filtered reference back to its real index for Manage.
                let idx = self
                    .owned
                    .iter()
                    .position(|m| m.registry == n.registry && m.label == n.label)
                    .unwrap_or(0);
                list = list.push(self.owned_row(t, n, idx));
            }
            body = body.push(list);
        }

        // Manage controls (refresh + manual add) only when not mid-search.
        if !has_query {
            body = body.push(Space::new().height(10));
            body = body.push(self.add_controls(t));
        }

        // ── "Across namespaces" — the cross-namespace availability rows.
        if has_query {
            body = body.push(Space::new().height(18));
            body = body.push(section_label(t, "ACROSS NAMESPACES"));
            body = body.push(Space::new().height(8));
            if self.searching && self.results.is_empty() {
                body = body.push(empty_hint(t, "Checking every namespace…"));
            } else {
                let mut list = column![].spacing(8).width(Length::Fill);
                for (i, hit) in self.results.iter().enumerate() {
                    list = list.push(self.result_row(t, hit, i));
                }
                body = body.push(list);
            }
        }

        // Reverse-lookup caveat.
        body = body.push(Space::new().height(16));
        body = body.push(
            text(
                "“Your names” are found by reverse lookup — the name each namespace says points \
                 back to you. Names you hold but haven't set as a reverse record won't appear; \
                 add them by name.",
            )
            .size(10)
            .color(t.sub)
            .font(mono()),
        );

        scroll(t, body.into())
    }

    fn add_controls<'a>(&self, t: KaoTheme) -> Element<'a, Message> {
        row![
            text_input("add a name you own, e.g. vitalik.eth", &self.add_input)
                .on_input(Message::AddInputChanged)
                .on_submit(Message::AddName)
                .padding(Padding::from([8, 12]))
                .size(13)
                .style(move |_, s| text_input_style(t, s)),
            Space::new().width(8),
            small_secondary_button(t, if self.adding { "…" } else { "Add" })
                .on_press(Message::AddName),
            Space::new().width(8),
            small_secondary_button(
                t,
                if self.scanning {
                    "Scanning…"
                } else {
                    "↻ Refresh"
                }
            )
            .on_press(Message::Refresh),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill)
        .into()
    }

    fn owned_row<'a>(&self, t: KaoTheme, n: &'a NameStatus, idx: usize) -> Element<'a, Message> {
        let badge = registry_badge(t, &n.registry);
        let title = text(n.full.clone()).size(15).color(t.text).font(bold());

        let (state_txt, state_col) = match n.state() {
            NameState::Active => (
                format!("expires in {}", fmt_days(n.seconds_remaining())),
                t.sub,
            ),
            NameState::Grace => ("in grace — renew now".to_string(), t.down),
            NameState::Permanent => ("permanent · immutable".to_string(), t.sub),
            NameState::Unregistered => ("expired".to_string(), t.down),
        };

        let info = row![badge, Space::new().width(8), title]
            .align_y(Alignment::Center)
            .width(Length::Fill);

        // State (and Manage, for the commit-reveal registrars) sit on the right;
        // the resolved address is intentionally omitted from the list — for XNS
        // it's just the owner again, and it lives in the Manage view for the rest.
        let mut right =
            row![text(state_txt).size(11).color(state_col).font(mono())].align_y(Alignment::Center);
        if n.registry.supports_renew() {
            right = right.push(Space::new().width(12));
            right =
                right.push(small_secondary_button(t, "Manage").on_press(Message::OpenManage(idx)));
        }

        card_row(t, info.into(), right.into())
    }

    fn result_row<'a>(&self, t: KaoTheme, hit: &'a SearchHit, idx: usize) -> Element<'a, Message> {
        let badge = registry_badge(t, &hit.registry);
        let title = text(hit.full.clone()).size(15).color(t.text).font(bold());

        let (kao, kao_col, status_line_el, right): (
            &str,
            Color,
            Element<'_, Message>,
            Element<'_, Message>,
        ) = match &hit.status {
            HitStatus::Available { quote } => {
                let price = match quote {
                    Some(q) if q.total == U256::ZERO => "free".to_string(),
                    Some(q) => format!("≈ {} ETH", fmt_eth(q.total)),
                    None => "price unavailable".to_string(),
                };
                let perm = if hit.registry.is_xns() {
                    " · permanent"
                } else {
                    ""
                };
                (
                    KAO_AVAILABLE,
                    t.up,
                    text(format!("available · {price}{perm}"))
                        .size(11)
                        .color(t.up)
                        .font(mono())
                        .into(),
                    pill_button(t, "Register", Message::PickResult(idx)),
                )
            }
            HitStatus::Taken { owner } => {
                let yours = *owner == Some(self.owner) || self.owns(&hit.registry, &hit.label);
                let label = if yours { "you own this" } else { "taken" };
                let col = if yours { t.a2 } else { t.sub };
                (
                    KAO_TAKEN,
                    t.sub,
                    text(label).size(11).color(col).font(mono()).into(),
                    Space::new().width(0).into(),
                )
            }
            HitStatus::Unavailable { reason } => (
                "·",
                t.sub,
                text(reason.clone())
                    .size(11)
                    .color(t.sub)
                    .font(mono())
                    .into(),
                Space::new().width(0).into(),
            ),
        };

        let info = column![
            row![
                badge,
                Space::new().width(8),
                title,
                Space::new().width(8),
                text(kao).size(13).color(kao_col),
            ]
            .align_y(Alignment::Center),
            Space::new().height(3),
            status_line_el,
        ]
        .width(Length::Fill);

        card_row(t, info.into(), right)
    }

    fn register_view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        let Some(r) = &self.reg else {
            return self.home_view(t);
        };
        let back = ghost_button(t, text("← Names").size(13).color(t.sub).font(bold()))
            .on_press(Message::Back);

        let header = row![
            registry_badge(t, &r.registry),
            Space::new().width(10),
            text(r.full.clone()).size(20).color(t.text).font(bold()),
        ]
        .align_y(Alignment::Center);

        let mut body = column![
            back,
            Space::new().height(10),
            header,
            Space::new().height(6)
        ]
        .width(Length::Fill)
        .max_width(560);

        // Sub-heading: how this namespace registers.
        let sub = if r.registry.is_commit_reveal() {
            "Two steps: commit, wait ~60s (anti-front-running), then register."
        } else {
            "One transaction. XNS names are permanent, immutable & non-transferable."
        };
        body = body.push(text(sub).size(12).color(t.sub));
        body = body.push(Space::new().height(16));

        // ENS duration stepper (only ENS honours a multi-year term).
        if r.registry == Registry::Ens {
            body = body.push(self.years_stepper(t, r.years));
            body = body.push(Space::new().height(16));
        }

        // XNS one-name-per-address heads-up.
        if r.registry.is_xns() && self.owned.iter().any(|n| n.registry.is_xns()) {
            body = body.push(
                text("Heads up: XNS allows one name per address, and you already hold one.")
                    .size(11)
                    .color(t.down),
            );
            body = body.push(Space::new().height(10));
        }

        body = body.push(self.reg_phase_view(t, r));
        scroll(t, body.into())
    }

    fn reg_phase_view<'a>(&self, t: KaoTheme, r: &'a RegisterFlow) -> Element<'a, Message> {
        match &r.phase {
            RegPhase::Ready { quote } => {
                let price = match quote {
                    Some(q) if q.total == U256::ZERO => "free".to_string(),
                    Some(q) => format!("≈ {} ETH", fmt_eth(q.total)),
                    None => "price unavailable".to_string(),
                };
                let btn_label = if r.registry.is_commit_reveal() {
                    "Register — step 1 of 2 (commit)"
                } else {
                    "Register"
                };
                column![
                    text(price).size(18).color(t.text).font(bold()),
                    Space::new().height(4),
                    text("plus network gas · excess is refunded on-chain")
                        .size(11)
                        .color(t.sub),
                    Space::new().height(16),
                    primary_button(t, btn_label, true).on_press(Message::StartRegister),
                ]
                .into()
            }
            RegPhase::Committing => status_line(t, "Committing… confirm on your device.", t.sub),
            RegPhase::Waiting { since, .. } => {
                let elapsed = crate::names::manage::now_secs().saturating_sub(*since);
                if elapsed > registrar::MAX_COMMITMENT_AGE {
                    return column![
                        status_line(t, "Commitment expired (waited over 24h).", t.down),
                        Space::new().height(10),
                        secondary_button(t, "Start over").on_press(Message::ResetRegister),
                    ]
                    .into();
                }
                let remaining = registrar::MIN_COMMITMENT_AGE.saturating_sub(elapsed);
                if remaining > 0 {
                    column![
                        status_line(
                            t,
                            &format!("Commit confirmed. Waiting {remaining}s before step 2…"),
                            t.sub,
                        ),
                        Space::new().height(6),
                        text("This pause stops anyone front-running your registration.")
                            .size(11)
                            .color(t.sub),
                    ]
                    .into()
                } else {
                    column![
                        status_line(t, "Ready to finish.", t.up),
                        Space::new().height(10),
                        primary_button(t, "Complete registration — step 2 of 2", true)
                            .on_press(Message::CompleteRegister),
                    ]
                    .into()
                }
            }
            RegPhase::Registering => status_line(t, "Registering… confirm on your device.", t.sub),
            RegPhase::Done => column![
                status_line(t, &format!("Registered {} {KAO_AVAILABLE}", r.full), t.up),
                Space::new().height(12),
                primary_button(t, "Back to my names", true).on_press(Message::Back),
            ]
            .into(),
            RegPhase::Failed(e) => column![
                status_line(t, e, t.down),
                Space::new().height(10),
                secondary_button(t, "Back").on_press(Message::ResetRegister),
            ]
            .into(),
        }
    }

    fn years_stepper<'a>(&self, t: KaoTheme, years: u32) -> Element<'a, Message> {
        row![
            text("Duration").size(13).color(t.sub),
            Space::new().width(Length::Fill),
            stepper_button(t, "−", Message::YearsDec),
            Space::new().width(10),
            text(format!(
                "{} year{}",
                years,
                if years == 1 { "" } else { "s" }
            ))
            .size(14)
            .color(t.text)
            .font(bold()),
            Space::new().width(10),
            stepper_button(t, "+", Message::YearsInc),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill)
        .into()
    }

    fn manage_view<'a>(&'a self, t: KaoTheme, idx: usize) -> Element<'a, Message> {
        let Some(n) = self.owned.get(idx) else {
            return self.home_view(t);
        };
        let back = ghost_button(t, text("← Names").size(13).color(t.sub).font(bold()))
            .on_press(Message::Back);

        let header = row![
            registry_badge(t, &n.registry),
            Space::new().width(10),
            text(n.full.clone()).size(20).color(t.text).font(bold()),
        ]
        .align_y(Alignment::Center);

        let (state_txt, state_col) = match n.state() {
            NameState::Active => (
                format!("Expires in {}", fmt_days(n.seconds_remaining())),
                t.sub,
            ),
            NameState::Grace => ("In grace period — renew now or lose it".to_string(), t.down),
            NameState::Permanent => ("Permanent · immutable".to_string(), t.sub),
            NameState::Unregistered => ("Expired".to_string(), t.down),
        };

        let mut body = column![
            back,
            Space::new().height(10),
            header,
            Space::new().height(6),
            text(state_txt).size(12).color(state_col).font(mono()),
            Space::new().height(18),
        ]
        .width(Length::Fill)
        .max_width(560);

        // ── Renew ──
        let renew_stepper = if n.registry == Registry::Ens {
            row![
                text("Add").size(13).color(t.sub),
                Space::new().width(Length::Fill),
                stepper_button(t, "−", Message::RenewYearsDec),
                Space::new().width(10),
                text(format!(
                    "{} year{}",
                    self.manage_years,
                    if self.manage_years == 1 { "" } else { "s" }
                ))
                .size(14)
                .color(t.text)
                .font(bold()),
                Space::new().width(10),
                stepper_button(t, "+", Message::RenewYearsInc),
            ]
            .align_y(Alignment::Center)
            .width(Length::Fill)
        } else {
            row![
                text("Renewal adds a fixed 1-year term")
                    .size(12)
                    .color(t.sub)
            ]
        };

        let renew_btn = primary_button(
            t,
            if self.manage_busy {
                "Working…"
            } else {
                "Renew"
            },
            true,
        )
        .on_press(Message::Renew);

        body = body.push(card(
            t,
            column![
                text("Prolong").size(13).color(t.text).font(bold()),
                Space::new().height(10),
                renew_stepper,
                Space::new().height(12),
                renew_btn,
            ]
            .into(),
        ));
        body = body.push(Space::new().height(14));

        // ── Set recipient ──
        let current = match n.recipient {
            Some(a) => row![text("now → ").size(11).color(t.sub), colored_address(t, a)]
                .align_y(Alignment::Center),
            None => row![text("no address record yet").size(11).color(t.sub)],
        };
        body = body.push(card(
            t,
            column![
                text("Set recipient").size(13).color(t.text).font(bold()),
                Space::new().height(4),
                text("the address this name resolves to (can differ from the owner)")
                    .size(11)
                    .color(t.sub),
                Space::new().height(8),
                current,
                Space::new().height(10),
                text_input("0x… recipient address", &self.manage_recipient)
                    .on_input(Message::ManageRecipientChanged)
                    .on_submit(Message::SetRecipient)
                    .padding(Padding::from([8, 12]))
                    .size(13)
                    .style(move |_, s| text_input_style(t, s)),
                Space::new().height(10),
                secondary_button(t, "Update recipient").on_press(Message::SetRecipient),
            ]
            .into(),
        ));

        if let Some((is_err, msg)) = &self.manage_notice {
            body = body.push(Space::new().height(12));
            body = body.push(
                text(msg.clone())
                    .size(12)
                    .color(if *is_err { t.down } else { t.up }),
            );
        }

        scroll(t, body.into())
    }
}

// ── small view helpers ──────────────────────────────────────────────────────

fn scroll<'a>(t: KaoTheme, content: Element<'a, Message>) -> Element<'a, Message> {
    iced::widget::scrollable(
        container(content)
            .center_x(Length::Fill)
            .padding(Padding::from([28, 32])),
    )
    .width(Length::Fill)
    .height(Length::Fill)
    .style(move |_, s| crate::ui::kao_widgets::kao_scrollable_style(t, s))
    .into()
}

fn section_label<'a>(t: KaoTheme, label: &'a str) -> Element<'a, Message> {
    text(label)
        .size(11)
        .color(t.sub)
        .font(crate::ui::kao_widgets::mono_bold())
        .into()
}

fn empty_hint<'a>(t: KaoTheme, msg: &'a str) -> Element<'a, Message> {
    container(text(msg).size(12).color(t.sub))
        .padding(Padding::from([14, 4]))
        .into()
}

/// A standard card with `info` on the left (filling) and `right` aligned at the
/// end.
fn card_row<'a>(
    t: KaoTheme,
    info: Element<'a, Message>,
    right: Element<'a, Message>,
) -> Element<'a, Message> {
    container(
        row![info, right]
            .align_y(Alignment::Center)
            .width(Length::Fill),
    )
    .padding(Padding::from([12, 14]))
    .width(Length::Fill)
    .style(move |_| container::Style {
        background: Some(Background::Color(t.card_alt)),
        border: Border {
            color: t.border,
            width: 1.0,
            radius: Radius::from(12),
        },
        text_color: Some(t.text),
        ..container::Style::default()
    })
    .into()
}

fn card<'a>(t: KaoTheme, inner: Element<'a, Message>) -> Element<'a, Message> {
    container(inner)
        .padding(Padding::from([14, 16]))
        .width(Length::Fill)
        .style(move |_| container::Style {
            background: Some(Background::Color(t.card)),
            border: Border {
                color: t.border,
                width: 1.0,
                radius: Radius::from(14),
            },
            text_color: Some(t.text),
            ..container::Style::default()
        })
        .into()
}

fn status_line<'a>(t: KaoTheme, msg: &str, color: iced::Color) -> Element<'a, Message> {
    let _ = t;
    text(msg.to_string()).size(13).color(color).into()
}

/// A compact accent CTA — the small, content-sized counterpart to the
/// full-width `primary_button`, for inline row actions (Search, Register).
fn pill_button<'a>(t: KaoTheme, label: &'a str, msg: Message) -> Element<'a, Message> {
    button(
        text(label.to_string())
            .size(13)
            .color(Color::WHITE)
            .font(bold()),
    )
    .padding(Padding::from([9, 18]))
    .on_press(msg)
    .style(move |_, status| button::Style {
        background: Some(Background::Color(match status {
            button::Status::Hovered | button::Status::Pressed => with_alpha(t.a1, 0.82),
            _ => t.a1,
        })),
        text_color: Color::WHITE,
        border: Border {
            color: Color::TRANSPARENT,
            width: 0.0,
            radius: Radius::from(10),
        },
        ..button::Style::default()
    })
    .into()
}

fn stepper_button<'a>(t: KaoTheme, glyph: &'a str, msg: Message) -> Element<'a, Message> {
    button(text(glyph).size(16).color(t.text).font(bold()))
        .padding(Padding::from([2, 12]))
        .on_press(msg)
        .style(move |_, status| button::Style {
            background: Some(Background::Color(match status {
                button::Status::Hovered | button::Status::Pressed => with_alpha(t.a1, 0.16),
                _ => t.card_alt,
            })),
            text_color: t.text,
            border: Border {
                color: t.border,
                width: 1.0,
                radius: Radius::from(8),
            },
            ..button::Style::default()
        })
        .into()
}

/// Accent per registry: ENS → a1, GNS → a2, WNS → a3, XNS → up (a distinct hue).
fn registry_accent(t: KaoTheme, r: &Registry) -> Color {
    match r {
        Registry::Ens => t.a1,
        Registry::Gns => t.a2,
        Registry::Wns => t.a3,
        Registry::Xns { .. } => t.up,
    }
}

fn registry_badge<'a>(t: KaoTheme, r: &Registry) -> Element<'a, Message> {
    let accent = registry_accent(t, r);
    container(
        text(r.badge().to_string())
            .size(10)
            .color(accent)
            .font(bold()),
    )
    .padding(Padding::from([2, 7]))
    .style(move |_| container::Style {
        background: Some(Background::Color(with_alpha(accent, 0.12))),
        border: Border {
            color: with_alpha(accent, 0.3),
            width: 1.0,
            radius: Radius::from(6),
        },
        ..container::Style::default()
    })
    .into()
}

/// Format wei as a short ETH string (up to 5 dp, trailing zeros trimmed).
fn fmt_eth(wei: U256) -> String {
    let s = alloy::primitives::utils::format_ether(wei);
    match s.parse::<f64>() {
        Ok(v) => {
            let formatted = format!("{v:.5}");
            formatted
                .trim_end_matches('0')
                .trim_end_matches('.')
                .to_string()
        }
        Err(_) => s,
    }
}

/// "340 days" / "1 day" / "12 hours" for a remaining-seconds count.
fn fmt_days(secs: u64) -> String {
    let days = secs / 86_400;
    if days >= 1 {
        format!("{days} day{}", if days == 1 { "" } else { "s" })
    } else {
        let hrs = secs / 3_600;
        format!("{hrs} hour{}", if hrs == 1 { "" } else { "s" })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::address;

    fn app() -> NamesApp {
        NamesApp::new(address!("0x000000000000000000000000000000000000bEEF"))
    }

    fn owned_status(registry: Registry, label: &str, owner: Address) -> NameStatus {
        let full = registry.full_name(label);
        NameStatus {
            registry,
            label: label.to_string(),
            full,
            expires_at: Some(crate::names::manage::now_secs() + registrar::YEAR_SECONDS),
            now: crate::names::manage::now_secs(),
            owner: Some(owner),
            recipient: Some(owner),
        }
    }

    #[test]
    fn on_open_kicks_off_one_reverse_scan() {
        let mut a = app();
        assert!(matches!(a.on_open(), Some(Outcome::ReverseScan)));
        assert!(a.scanning);
        // Only once.
        assert!(a.on_open().is_none());
    }

    #[test]
    fn bare_query_searches_all_default_namespaces() {
        let mut a = app();
        a.update(Message::QueryChanged("rat".into()));
        let out = a.update(Message::Search);
        match out {
            Some(Outcome::Search { label, registries }) => {
                assert_eq!(label, "rat");
                assert_eq!(registries.len(), 5);
            }
            _ => panic!("expected Search, got {out:?}"),
        }
        assert!(a.searching);
    }

    #[test]
    fn explicit_xns_query_searches_one_namespace() {
        let mut a = app();
        a.update(Message::QueryChanged("cow.cheese".into()));
        let out = a.update(Message::Search);
        match out {
            Some(Outcome::Search { label, registries }) => {
                assert_eq!(label, "cow");
                assert_eq!(
                    registries,
                    vec![Registry::Xns {
                        namespace: "cheese".to_string()
                    }]
                );
            }
            _ => panic!("expected Search, got {out:?}"),
        }
    }

    #[test]
    fn pick_available_result_opens_register_panel() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Xns {
                namespace: "crops".to_string(),
            },
            label: "cow".to_string(),
            full: "cow.crops".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        assert_eq!(a.view, View::Register);
        // XNS register is a single step → StartRegister emits RegisterXns.
        let out = a.update(Message::StartRegister);
        match out {
            Some(Outcome::RegisterXns { namespace, label }) => {
                assert_eq!(namespace, "crops");
                assert_eq!(label, "cow");
            }
            _ => panic!("expected RegisterXns, got {out:?}"),
        }
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Registering
        ));
    }

    #[test]
    fn pick_taken_result_does_nothing() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Ens,
            label: "vitalik".to_string(),
            full: "vitalik.eth".to_string(),
            status: HitStatus::Taken { owner: None },
        }];
        a.update(Message::PickResult(0));
        assert_eq!(a.view, View::Home, "taken names aren't registerable");
        assert!(a.reg.is_none());
    }

    #[test]
    fn legacy_register_runs_commit_then_reveal() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Gns,
            label: "apoorv".to_string(),
            full: "apoorv.gwei".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        // Step 1: commit.
        let out = a.update(Message::StartRegister);
        assert!(matches!(out, Some(Outcome::Commit { .. })));
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Committing
        ));
        // Coordinator reports commit mined → Waiting.
        let plan = RegisterPlan {
            namespace: Namespace::Gns,
            label: "apoorv".into(),
            owner: a.owner,
            duration_secs: registrar::YEAR_SECONDS,
            secret: alloy::primitives::B256::repeat_byte(7),
        };
        a.on_commit(Ok((plan, TxHash::ZERO)));
        // Too early → no reveal.
        assert!(a.update(Message::CompleteRegister).is_none());
        // Backdate past the 60s window → reveal allowed.
        if let Some(RegisterFlow {
            phase: RegPhase::Waiting { since, .. },
            ..
        }) = &mut a.reg
        {
            *since = crate::names::manage::now_secs() - registrar::MIN_COMMITMENT_AGE - 1;
        }
        let out = a.update(Message::CompleteRegister);
        assert!(matches!(out, Some(Outcome::Register { .. })));
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Registering
        ));
    }

    #[test]
    fn complete_register_blocked_after_max_commitment_age() {
        let mut a = app();
        a.reg = Some(RegisterFlow {
            registry: Registry::Gns,
            label: "apoorv".into(),
            full: "apoorv.gwei".into(),
            years: 1,
            phase: RegPhase::Waiting {
                plan: RegisterPlan {
                    namespace: Namespace::Gns,
                    label: "apoorv".into(),
                    owner: a.owner,
                    duration_secs: registrar::YEAR_SECONDS,
                    secret: alloy::primitives::B256::repeat_byte(7),
                },
                since: crate::names::manage::now_secs()
                    .saturating_sub(registrar::MAX_COMMITMENT_AGE + 1),
            },
        });
        assert!(a.update(Message::CompleteRegister).is_none());
        assert!(matches!(a.reg.as_ref().unwrap().phase, RegPhase::Failed(_)));
    }

    #[test]
    fn add_name_rejects_bare_label() {
        let mut a = app();
        a.update(Message::AddInputChanged("rat".into()));
        assert!(a.update(Message::AddName).is_none());
        assert!(a.notice.as_ref().unwrap().0, "notice is an error");
    }

    #[test]
    fn on_status_only_keeps_owned_names() {
        let mut a = app();
        a.on_status(Ok(owned_status(Registry::Gns, "apoorv", a.owner)));
        assert_eq!(a.owned.len(), 1);
        a.on_status(Ok(owned_status(
            Registry::Ens,
            "vitalik",
            address!("0x00000000000000000000000000000000DeaDBeef"),
        )));
        assert_eq!(a.owned.len(), 1, "not-owned name must not be added");
        assert!(a.notice.as_ref().unwrap().0);
    }

    #[test]
    fn xns_owned_name_has_no_manage() {
        // OpenManage on an XNS row is a no-op (nothing to renew/re-point).
        let mut a = app();
        let mut s = owned_status(
            Registry::Xns {
                namespace: "xns".to_string(),
            },
            "alice",
            a.owner,
        );
        s.expires_at = None;
        a.owned.push(s);
        a.update(Message::OpenManage(0));
        assert_eq!(a.view, View::Home, "XNS has no manage view");
    }

    #[test]
    fn manage_set_recipient_validates_address() {
        let mut a = app();
        a.on_status(Ok(owned_status(Registry::Gns, "apoorv", a.owner)));
        a.update(Message::OpenManage(0));
        assert_eq!(a.view, View::Manage(0));
        a.update(Message::ManageRecipientChanged("nope".into()));
        assert!(a.update(Message::SetRecipient).is_none());
        assert!(a.manage_notice.as_ref().unwrap().0);
        a.update(Message::ManageRecipientChanged(
            "0x00000000000000000000000000000000DeaDBeef".into(),
        ));
        let out = a.update(Message::SetRecipient);
        assert!(matches!(out, Some(Outcome::SetRecipient { .. })));
        assert!(a.manage_busy);
    }
}
