//! Name-service app — a search-first surface for registering and managing names
//! across ENS (`.eth`), GNS (`.gwei`), WNS (`.wei`) and XNS (`.xns`, `.crops`
//! and any permissionless namespace), surfaced as a tile in the Apps launcher.
//!
//! This pane is a self-contained Elm widget: it owns ephemeral UI state and emits
//! [`Outcome`]s for the coordinator to turn into verified reads / signed
//! transactions, and never touches the network itself.
//!
//! - **Home** — one big search bar. Empty, it lists the names that resolve to the
//!   active account (reverse-lookup discovery, plus manual add). Typed, it checks
//!   the label across every namespace and filters your own names by it.
//! - **Register** — a focused panel for one name: the two-step commit → wait 60s
//!   → reveal flow for the commit-reveal registrars, or XNS's single transaction.
//! - **Manage** — renew / re-point an owned commit-reveal name (XNS names are
//!   permanent + immutable, so they have nothing to manage).
//!
//! The commit/reveal `secret` is generated by the coordinator (which owns the
//! RNG), handed back inside the [`RegisterPlan`] on a successful commit, and
//! replayed verbatim on the reveal — so the two transactions agree by
//! construction.

use std::time::Duration;

use alloy::primitives::{Address, TxHash, U256};
use iced::border::Radius;
use iced::widget::{Space, button, column, container, row, text, text_input};
use iced::{Alignment, Background, Border, Color, Element, Length, Padding, Subscription};

use crate::names::manage::{HitStatus, NameState, NameStatus, Query, Registry, SearchHit};
use crate::names::registrar::{self, Namespace, RegisterPlan};
use crate::ui::kao_theme::{KaoTheme, with_alpha};
use crate::ui::kao_widgets::{
    bold, colored_address, ghost_button, mono, primary_button, screen_subtitle, screen_title,
    secondary_button, small_secondary_button, text_input_style,
};

/// ENS registration term bounds (years). GNS/WNS grant a fixed 365-day term and
/// XNS names are permanent; both ignore this.
const MIN_YEARS: u32 = 1;
const MAX_YEARS: u32 = 10;

/// Auto-search debounce: poll cadence while there's unsubmitted input, and the
/// number of quiet polls (each keystroke resets the count) before the search
/// fires on its own. ~2 × 250ms ⇒ the search lands roughly a third of a second
/// after the user stops typing.
const DEBOUNCE_INTERVAL: Duration = Duration::from_millis(250);
const DEBOUNCE_TICKS: u32 = 2;

// Kaomoji palette for the surface.
const KAO_MASCOT: &str = "(๑>؂•̀๑)";
const KAO_AVAILABLE: &str = "(๑ᵔ⤙ᵔ๑)";
const KAO_TAKEN: &str = "(*ᴗ͈ˬᴗ͈)ꕤ*.ﾟ";

#[derive(Debug, Clone)]
pub enum Message {
    // ── search ──
    QueryChanged(String),
    Search,
    /// Debounce heartbeat: fires the cross-namespace search automatically once
    /// typing has settled, so the user doesn't have to press Enter.
    DebounceTick,
    Refresh,
    // ── owned: manual add ──
    AddInputChanged(String),
    AddName,
    OpenManage(usize),
    // ── navigation ──
    Back,
    // ── register panel ──
    PickResult(usize),
    YearsDec,
    YearsInc,
    StartRegister,
    CompleteRegister,
    ResetRegister,
    // ── manage ──
    RenewYearsDec,
    RenewYearsInc,
    Renew,
    ManageRecipientChanged(String),
    SetRecipient,
    // ── timer for the commit→reveal wait ──
    Tick,
}

/// Requests the pane bubbles up to the coordinator.
#[derive(Debug, Clone)]
pub enum Outcome {
    /// Discover names that resolve to the active account (reverse lookup).
    ReverseScan,
    /// Check `label` across `registries` (availability + price). `seq` round-trips
    /// so a reply for a superseded query can be dropped (see [`NamesApp::on_search`]).
    Search {
        seq: u64,
        label: String,
        registries: Vec<Registry>,
    },
    /// Re-price an ENS registration for a new term (read-only). Only ENS, whose
    /// rent scales with the duration; the result refreshes the panel's quote so
    /// the price shown matches the years the user picked. `years` round-trips so
    /// a result that lands after the user has clicked again can be dropped.
    Quote {
        namespace: Namespace,
        label: String,
        years: u32,
    },
    /// Verify one manually-entered name's status (for manual add).
    Status { registry: Registry, label: String },
    /// Commit-reveal step 1 (ENS/GNS/WNS). The name is always registered to the
    /// signing account (`reveal` mints to `msg.sender`); a different recipient is
    /// set afterward.
    Commit {
        namespace: Namespace,
        label: String,
        years: u32,
    },
    /// Commit-reveal step 2: broadcast the reveal/register for the committed plan.
    Register { plan: RegisterPlan },
    /// XNS one-shot registration. The name is bound to (and resolves to) the
    /// signing account, immutably.
    RegisterXns { namespace: String, label: String },
    /// Renew ("prolong") an owned commit-reveal name.
    Renew {
        namespace: Namespace,
        label: String,
        years: u32,
    },
    /// Point an owned commit-reveal name at `recipient`.
    SetRecipient {
        namespace: Namespace,
        label: String,
        recipient: Address,
    },
}

/// Which sub-view is showing.
#[derive(Debug, Clone, PartialEq, Eq)]
enum View {
    Home,
    Register,
    Manage(usize),
}

/// The registration flow's state machine. XNS skips `Committing`/`Waiting`.
#[derive(Debug, Clone)]
enum RegPhase {
    /// Picked from search; price quoted, ready to start.
    Ready {
        quote: Option<crate::names::manage::RegisterQuote>,
    },
    /// Commit broadcast in flight (commit-reveal only).
    Committing,
    /// Commit mined; counting down `MIN_COMMITMENT_AGE` before the reveal.
    Waiting { plan: RegisterPlan, since: u64 },
    /// Reveal/register broadcast in flight.
    Registering,
    /// Registered.
    Done,
    /// A step failed.
    Failed(String),
}

/// The focused registration panel's target + state.
#[derive(Debug, Clone)]
struct RegisterFlow {
    registry: Registry,
    label: String,
    full: String,
    years: u32,
    /// An ENS re-quote (after a duration change) is in flight — the price shows
    /// "calculating…" until [`NamesApp::on_quote`] lands.
    quoting: bool,
    phase: RegPhase,
}

#[derive(Debug)]
pub struct NamesApp {
    owner: Address,
    view: View,
    /// Whether the initial reverse scan has been kicked off yet.
    loaded: bool,

    // Search
    query: String,
    searching: bool,
    /// Monotonic search id, bumped on every edit and per [`NamesApp::run_search`],
    /// round-tripped through the reply so a slow result for a query the user has
    /// since changed is dropped instead of painting over the current one.
    search_seq: u64,
    /// An auto-search is scheduled: the box has text the user hasn't submitted yet.
    /// Drives the debounce subscription and the in-progress display.
    pending_search: bool,
    /// Quiet [`DEBOUNCE_INTERVAL`] polls since the last keystroke; reset on edit.
    idle_ticks: u32,
    results: Vec<SearchHit>,

    // Owned (reverse lookup + manual add)
    owned: Vec<NameStatus>,
    scanning: bool,
    notice: Option<(bool, String)>,
    add_input: String,
    adding: bool,

    // Register panel
    reg: Option<RegisterFlow>,

    // Manage panel
    manage_years: u32,
    manage_recipient: String,
    manage_busy: bool,
    manage_notice: Option<(bool, String)>,
}

impl NamesApp {
    pub fn new(owner: Address) -> Self {
        Self {
            owner,
            view: View::Home,
            loaded: false,
            query: String::new(),
            searching: false,
            search_seq: 0,
            pending_search: false,
            idle_ticks: 0,
            results: Vec::new(),
            owned: Vec::new(),
            scanning: false,
            notice: None,
            add_input: String::new(),
            adding: false,
            reg: None,
            manage_years: 1,
            manage_recipient: String::new(),
            manage_busy: false,
            manage_notice: None,
        }
    }

    /// Called when the app is opened from the launcher — kicks off the reverse
    /// scan once so "your names" populates without a manual tap.
    pub fn on_open(&mut self) -> Option<Outcome> {
        if self.loaded {
            return None;
        }
        self.loaded = true;
        self.scanning = true;
        Some(Outcome::ReverseScan)
    }

    /// Two independent timers, each subscribed only while it's needed: a 1-second
    /// tick driving the commit→reveal countdown, and a faster debounce poll that
    /// auto-fires the search once typing settles.
    pub fn subscription(&self) -> Subscription<Message> {
        let reg_active = matches!(
            self.reg.as_ref().map(|r| &r.phase),
            Some(RegPhase::Committing | RegPhase::Waiting { .. } | RegPhase::Registering)
        );
        let mut subs = Vec::new();
        if reg_active {
            subs.push(iced::time::every(Duration::from_secs(1)).map(|_| Message::Tick));
        }
        if self.pending_search {
            subs.push(iced::time::every(DEBOUNCE_INTERVAL).map(|_| Message::DebounceTick));
        }
        Subscription::batch(subs)
    }

    pub fn update(&mut self, msg: Message) -> Option<Outcome> {
        match msg {
            Message::Tick => None,

            // ── search ──
            Message::QueryChanged(s) => {
                self.query = s;
                // Any edit makes the on-screen rows stale: drop them at once (so
                // the previous query's results can't show under the new text) and
                // invalidate a search already in flight — its reply is dropped by
                // the seq guard in `on_search`.
                self.results.clear();
                self.searching = false;
                self.search_seq += 1;
                self.idle_ticks = 0;
                // Non-empty box ⇒ schedule an auto-search; empty ⇒ leave search mode.
                self.pending_search = !self.query.trim().is_empty();
                None
            }
            Message::Search => self.run_search(),
            Message::DebounceTick => {
                if !self.pending_search {
                    return None;
                }
                self.idle_ticks += 1;
                if self.idle_ticks < DEBOUNCE_TICKS {
                    return None;
                }
                // Typing has settled. Only auto-fire a query that parses cleanly —
                // a half-typed one (e.g. "cow.") just waits for more input rather
                // than flashing a parse error the user didn't ask for.
                self.pending_search = false;
                if crate::names::manage::parse_query(&self.query).is_ok() {
                    self.run_search()
                } else {
                    None
                }
            }
            Message::Refresh => {
                if self.scanning {
                    return None;
                }
                self.scanning = true;
                self.notice = None;
                Some(Outcome::ReverseScan)
            }

            // ── owned: manual add ──
            Message::AddInputChanged(s) => {
                self.add_input = s;
                None
            }
            Message::AddName => {
                if self.adding {
                    return None;
                }
                match crate::names::manage::parse_one_name(&self.add_input) {
                    Ok((registry, label)) => {
                        self.adding = true;
                        self.notice = None;
                        Some(Outcome::Status { registry, label })
                    }
                    Err(e) => {
                        self.notice = Some((true, e));
                        None
                    }
                }
            }
            Message::OpenManage(idx) => {
                if let Some(n) = self.owned.get(idx)
                    && n.registry.supports_renew()
                {
                    self.manage_years = 1;
                    self.manage_recipient = String::new();
                    self.manage_busy = false;
                    self.manage_notice = None;
                    self.view = View::Manage(idx);
                }
                None
            }

            // ── nav ──
            Message::Back => {
                self.view = View::Home;
                self.reg = None;
                None
            }

            // ── register panel ──
            Message::PickResult(idx) => {
                if let Some(hit) = self.results.get(idx)
                    && let HitStatus::Available { quote } = &hit.status
                {
                    self.reg = Some(RegisterFlow {
                        registry: hit.registry.clone(),
                        label: hit.label.clone(),
                        full: hit.full.clone(),
                        years: 1,
                        quoting: false,
                        phase: RegPhase::Ready { quote: *quote },
                    });
                    self.view = View::Register;
                }
                None
            }
            Message::YearsDec => {
                let prev = self.reg.as_ref().map(|r| r.years);
                if let Some(r) = &mut self.reg {
                    r.years = r.years.saturating_sub(1).max(MIN_YEARS);
                }
                self.requote_if_changed(prev)
            }
            Message::YearsInc => {
                let prev = self.reg.as_ref().map(|r| r.years);
                if let Some(r) = &mut self.reg {
                    r.years = (r.years + 1).min(MAX_YEARS);
                }
                self.requote_if_changed(prev)
            }
            Message::StartRegister => self.start_register(),
            Message::CompleteRegister => self.complete_register(),
            Message::ResetRegister => {
                self.view = View::Home;
                self.reg = None;
                None
            }

            // ── manage ──
            Message::RenewYearsDec => {
                self.manage_years = self.manage_years.saturating_sub(1).max(MIN_YEARS);
                None
            }
            Message::RenewYearsInc => {
                self.manage_years = (self.manage_years + 1).min(MAX_YEARS);
                None
            }
            Message::Renew => {
                let View::Manage(idx) = self.view else {
                    return None;
                };
                let n = self.owned.get(idx)?;
                let ns = n.registry.legacy()?;
                if self.manage_busy {
                    return None;
                }
                // Busy flag is set on confirm (`begin_manage`), not here — the
                // review overlay opens first; cancelling leaves the card idle.
                self.manage_notice = None;
                Some(Outcome::Renew {
                    namespace: ns,
                    label: n.label.clone(),
                    years: self.manage_years,
                })
            }
            Message::ManageRecipientChanged(s) => {
                self.manage_recipient = s;
                None
            }
            Message::SetRecipient => {
                let View::Manage(idx) = self.view else {
                    return None;
                };
                let n = self.owned.get(idx)?;
                let ns = n.registry.legacy()?;
                if self.manage_busy {
                    return None;
                }
                let recipient = match self.manage_recipient.trim().parse::<Address>() {
                    Ok(a) => a,
                    Err(_) => {
                        self.manage_notice = Some((true, "enter a valid 0x… address".to_string()));
                        return None;
                    }
                };
                // Busy flag is set on confirm (`begin_manage`); the review opens
                // first.
                self.manage_notice = None;
                Some(Outcome::SetRecipient {
                    namespace: ns,
                    label: n.label.clone(),
                    recipient,
                })
            }
        }
    }

    /// Parse the search bar and emit the cross-namespace check. Cancels any
    /// scheduled auto-search (this *is* the search) and supersedes an in-flight one.
    fn run_search(&mut self) -> Option<Outcome> {
        self.pending_search = false;
        let parsed = match crate::names::manage::parse_query(&self.query) {
            Ok(q) => q,
            Err(e) => {
                self.notice = Some((true, e));
                return None;
            }
        };
        // Drop the previous run's rows so the in-flight view shows the "checking…"
        // hint instead of stale results; the bumped seq drops a late reply for an
        // earlier query.
        self.results.clear();
        self.searching = true;
        self.notice = None;
        self.search_seq += 1;
        let seq = self.search_seq;
        match parsed {
            Query::Bare(label) => Some(Outcome::Search {
                seq,
                label,
                registries: Registry::defaults(),
            }),
            Query::One { registry, label } => Some(Outcome::Search {
                seq,
                label,
                registries: vec![registry],
            }),
        }
    }

    /// After the duration stepper moves, kick off a fresh ENS quote so the
    /// displayed price tracks the chosen term. No-op for non-ENS (only ENS shows
    /// the stepper and scales with duration) or if the value didn't actually
    /// change (already at a bound), so a click on a disabled bound doesn't spam
    /// reads.
    fn requote_if_changed(&mut self, prev_years: Option<u32>) -> Option<Outcome> {
        let r = self.reg.as_mut()?;
        if Some(r.years) == prev_years {
            return None;
        }
        let ns = r.registry.legacy()?;
        if ns != Namespace::Ens || !matches!(r.phase, RegPhase::Ready { .. }) {
            return None;
        }
        r.quoting = true;
        Some(Outcome::Quote {
            namespace: ns,
            label: r.label.clone(),
            years: r.years,
        })
    }

    /// Begin registration for the focused name — commit (legacy) or one-shot
    /// register (XNS).
    fn start_register(&mut self) -> Option<Outcome> {
        let r = self.reg.as_mut()?;
        if !matches!(r.phase, RegPhase::Ready { .. } | RegPhase::Failed(_)) {
            return None;
        }
        // Don't flip to a busy phase here — the coordinator opens the
        // clear-signing review first and only drives us into Committing /
        // Registering (via `begin_commit` / `begin_reveal`) once the user
        // confirms. A cancel leaves the Ready phase (and its quote) intact.
        match r.registry.legacy() {
            Some(ns) => Some(Outcome::Commit {
                namespace: ns,
                label: r.label.clone(),
                years: r.years,
            }),
            None => {
                let namespace = r.registry.xns_namespace()?.to_string();
                Some(Outcome::RegisterXns {
                    namespace,
                    label: r.label.clone(),
                })
            }
        }
    }

    /// Finish the commit-reveal flow (step 2). Guards both the 60s minimum and
    /// the 24h maximum so a late click doesn't broadcast an expired commitment.
    fn complete_register(&mut self) -> Option<Outcome> {
        let r = self.reg.as_mut()?;
        let RegPhase::Waiting { plan, since } = &r.phase else {
            return None;
        };
        let elapsed = crate::names::manage::now_secs().saturating_sub(*since);
        if elapsed < registrar::MIN_COMMITMENT_AGE {
            return None;
        }
        if elapsed > registrar::MAX_COMMITMENT_AGE {
            r.phase =
                RegPhase::Failed("commitment expired (waited over 24h) — start over".to_string());
            return None;
        }
        // Stay in Waiting until the user confirms the review; `begin_reveal`
        // flips us to Registering at that point.
        let plan = plan.clone();
        Some(Outcome::Register { plan })
    }

    // ── review-confirmed phase flips (coordinator → pane) ──────────────────────
    // The coordinator calls these once the user confirms the clear-signing review,
    // mirroring the phase the pane used to enter the instant its button was
    // pressed. Splitting it out is what lets a *cancel* leave the pane untouched.

    /// Commit-reveal step 1 confirmed — broadcast in flight.
    pub fn begin_commit(&mut self) {
        if let Some(r) = &mut self.reg {
            r.phase = RegPhase::Committing;
        }
    }

    /// Reveal (or XNS one-shot) confirmed — broadcast in flight.
    pub fn begin_reveal(&mut self) {
        if let Some(r) = &mut self.reg {
            r.phase = RegPhase::Registering;
        }
    }

    /// A manage write (renew / set-recipient) confirmed — mark the card busy.
    pub fn begin_manage(&mut self) {
        self.manage_busy = true;
    }

    // ── result callbacks (coordinator → pane) ─────────────────────────────────

    pub fn on_reverse_scan(&mut self, result: Result<Vec<NameStatus>, String>) {
        self.scanning = false;
        match result {
            Ok(found) => {
                let n = found.len();
                self.merge_owned(found);
                self.notice = Some((
                    false,
                    if self.owned.is_empty() {
                        "No names point to this account yet.".to_string()
                    } else {
                        format!("{n} name(s) resolve to you.")
                    },
                ));
            }
            Err(e) => self.notice = Some((true, format!("Scan failed: {e}"))),
        }
    }

    pub fn on_search(&mut self, seq: u64, result: Result<Vec<SearchHit>, String>) {
        // Ignore a reply for a search the user has already moved past: it would
        // otherwise clear the spinner and paint the old query's rows under the
        // one now in flight (or leave `searching` wrongly false).
        if seq != self.search_seq {
            return;
        }
        self.searching = false;
        match result {
            Ok(hits) => self.results = hits,
            Err(e) => {
                self.results.clear();
                self.notice = Some((true, e));
            }
        }
    }

    /// Result of a duration-change re-quote (ENS). Refreshes the panel's price.
    /// Dropped if the user has since changed the term again (the in-flight
    /// `years` no longer matches the panel) or has left the Ready phase.
    pub fn on_quote(
        &mut self,
        years: u32,
        result: Result<crate::names::manage::RegisterQuote, String>,
    ) {
        let Some(r) = &mut self.reg else { return };
        if r.years != years {
            return;
        }
        r.quoting = false;
        if let RegPhase::Ready { quote } = &mut r.phase {
            *quote = result.ok();
        }
    }

    pub fn on_status(&mut self, result: Result<NameStatus, String>) {
        self.adding = false;
        match result {
            Ok(status) => {
                if status.owned_by(self.owner) && status.state() != NameState::Unregistered {
                    self.add_input.clear();
                    let full = status.full.clone();
                    self.merge_owned(vec![status]);
                    self.notice = Some((false, format!("Added {full}.")));
                } else {
                    self.notice = Some((true, "that name isn't held by this account".to_string()));
                }
            }
            Err(e) => self.notice = Some((true, e)),
        }
    }

    pub fn on_commit(&mut self, result: Result<(RegisterPlan, TxHash), String>) {
        let Some(r) = &mut self.reg else { return };
        match result {
            Ok((plan, _hash)) => {
                r.phase = RegPhase::Waiting {
                    plan,
                    since: crate::names::manage::now_secs(),
                };
            }
            Err(e) => r.phase = RegPhase::Failed(e),
        }
    }

    pub fn on_register(&mut self, result: Result<(String, TxHash), String>) {
        // Pull the registered target out of the flow (and flip its phase) before
        // touching the rest of `self`, so the success path can update the search
        // row and owned list without holding the `self.reg` borrow.
        let registered = match result {
            Ok(_) => {
                let Some(r) = &mut self.reg else { return };
                r.phase = RegPhase::Done;
                Some((r.registry.clone(), r.label.clone(), r.full.clone(), r.years))
            }
            Err(e) => {
                if let Some(r) = &mut self.reg {
                    r.phase = RegPhase::Failed(e);
                }
                None
            }
        };
        if let Some((registry, label, full, years)) = registered {
            self.register_succeeded(&registry, &label, &full, years);
        }
    }

    /// Reflect a just-broadcast registration locally — without a read-back, since
    /// the tx isn't mined yet and a verified status read would still see the name
    /// as free. (a) The search row that offered this name flips to "you own this"
    /// (no more Register button); (b) the name joins "Your names" with the facts
    /// we just signed: owner + recipient are the signing account (the commit-reveal
    /// reveal mints to `msg.sender`; XNS binds both to `msg.sender` immutably), and
    /// the expiry follows the term (ENS scales with the chosen years; GNS/WNS grant
    /// a fixed 1-year term; XNS names are permanent). A later Refresh re-verifies.
    fn register_succeeded(&mut self, registry: &Registry, label: &str, full: &str, years: u32) {
        if let Some(hit) = self
            .results
            .iter_mut()
            .find(|h| &h.registry == registry && h.label == label)
        {
            hit.status = HitStatus::Taken {
                owner: Some(self.owner),
            };
        }
        let now = crate::names::manage::now_secs();
        let expires_at = match registry {
            Registry::Ens => Some(now + registrar::ens_duration_secs(years)),
            Registry::Gns | Registry::Wns => Some(now + registrar::YEAR_SECONDS),
            Registry::Xns { .. } => None,
        };
        self.merge_owned(vec![NameStatus {
            registry: registry.clone(),
            label: label.to_string(),
            full: full.to_string(),
            expires_at,
            now,
            owner: Some(self.owner),
            recipient: Some(self.owner),
        }]);
    }

    pub fn on_renew(&mut self, result: Result<(String, TxHash), String>) {
        self.manage_busy = false;
        match result {
            Ok((name, _)) => self.manage_notice = Some((false, format!("Renewed {name}."))),
            Err(e) => self.manage_notice = Some((true, e)),
        }
    }

    pub fn on_set_recipient(&mut self, result: Result<(String, TxHash), String>) {
        self.manage_busy = false;
        match result {
            Ok((name, _)) => {
                self.manage_recipient.clear();
                self.manage_notice = Some((false, format!("Updated {name}'s recipient.")));
            }
            Err(e) => self.manage_notice = Some((true, e)),
        }
    }

    /// Upsert by (registry, label) so a re-scan or manual re-add refreshes a row
    /// rather than duplicating it.
    fn merge_owned(&mut self, incoming: Vec<NameStatus>) {
        for n in incoming {
            if let Some(existing) = self
                .owned
                .iter_mut()
                .find(|e| e.registry == n.registry && e.label == n.label)
            {
                *existing = n;
            } else {
                self.owned.push(n);
            }
        }
        self.owned.sort_by(|a, b| {
            a.full
                .cmp(&b.full)
                .then(a.registry.badge().cmp(b.registry.badge()))
        });
    }

    /// Whether the active account owns `label` in `registry` (cross-reference for
    /// "you own this" on a search row whose `Taken` carries no owner).
    fn owns(&self, registry: &Registry, label: &str) -> bool {
        self.owned
            .iter()
            .any(|n| &n.registry == registry && n.label == label)
    }

    // ── views ─────────────────────────────────────────────────────────────────

    pub fn view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        match &self.view {
            View::Home => self.home_view(t),
            View::Register => self.register_view(t),
            View::Manage(idx) => self.manage_view(t, *idx),
        }
    }

    fn home_view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        let header = row![
            column![
                screen_title(t, "Names"),
                Space::new().height(4),
                screen_subtitle(t, "Search & register across .eth / .gwei / .wei / .xns"),
            ]
            .width(Length::Fill),
            text(KAO_MASCOT).size(22).color(t.a3).font(bold()),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill);

        // The big search bar — primary interaction. The input fills; the action
        // is a compact pill so the bar gets the room.
        let search = row![
            text_input(
                "search a name — kitty, vitalik.eth, cow.crops…",
                &self.query
            )
            .on_input(Message::QueryChanged)
            .on_submit(Message::Search)
            .padding(Padding::from([14, 18]))
            .size(16)
            .width(Length::Fill)
            .style(move |_, s| text_input_style(t, s)),
            Space::new().width(10),
            pill_button(
                t,
                if self.searching { "…" } else { "Search" },
                Message::Search
            ),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill);

        let mut body = column![
            header,
            Space::new().height(16),
            search,
            Space::new().height(10)
        ]
        .width(Length::Fill)
        .max_width(640);

        if let Some((is_err, msg)) = &self.notice {
            body =
                body.push(
                    text(msg.clone())
                        .size(12)
                        .color(if *is_err { t.down } else { t.sub }),
                );
            body = body.push(Space::new().height(8));
        }

        // Search mode begins the moment there's text in the box — the rows below
        // track what's typed now, not the last submitted query.
        let trimmed = self.query.trim();
        let has_query = !trimmed.is_empty();

        // ── "Your names" — reverse-discovered + manually added, filtered live by
        //    the typed text so the search bar searches over them too.
        let filter = has_query.then(|| trimmed.to_ascii_lowercase());
        let owned_rows: Vec<&NameStatus> = self
            .owned
            .iter()
            .filter(|n| match &filter {
                Some(q) => n.full.to_ascii_lowercase().contains(q) || n.label.contains(q),
                None => true,
            })
            .collect();

        body = body.push(section_label(t, "YOUR NAMES"));
        body = body.push(Space::new().height(8));
        if owned_rows.is_empty() {
            let msg = if self.scanning {
                "Looking up names that point to you…"
            } else if has_query {
                "None of your names match that."
            } else {
                "No names point to this account yet. Register one below, or add one you own."
            };
            body = body.push(empty_hint(t, msg));
        } else {
            let mut list = column![].spacing(8).width(Length::Fill);
            for n in &owned_rows {
                // Map the filtered reference back to its real index for Manage.
                let idx = self
                    .owned
                    .iter()
                    .position(|m| m.registry == n.registry && m.label == n.label)
                    .unwrap_or(0);
                list = list.push(self.owned_row(t, n, idx));
            }
            body = body.push(list);
        }

        // Manage controls (refresh + manual add) only when not mid-search.
        if !has_query {
            body = body.push(Space::new().height(10));
            body = body.push(self.add_controls(t));
        }

        // ── "Across namespaces" — the cross-namespace availability rows.
        if has_query {
            body = body.push(Space::new().height(18));
            body = body.push(section_label(t, "ACROSS NAMESPACES"));
            body = body.push(Space::new().height(8));
            if self.pending_search || self.searching {
                // Typing in progress, debounce pending, or a search in flight —
                // show the progress hint, never the previous query's rows (which
                // were cleared on the edit anyway).
                body = body.push(empty_hint(t, "Checking every namespace…"));
            } else {
                let mut list = column![].spacing(8).width(Length::Fill);
                for (i, hit) in self.results.iter().enumerate() {
                    list = list.push(self.result_row(t, hit, i));
                }
                body = body.push(list);
            }
        }

        // Reverse-lookup caveat.
        body = body.push(Space::new().height(16));
        body = body.push(
            text(
                "“Your names” are found by reverse lookup — the name each namespace says points \
                 back to you. Names you hold but haven't set as a reverse record won't appear; \
                 add them by name.",
            )
            .size(10)
            .color(t.sub)
            .font(mono()),
        );

        scroll(t, body.into())
    }

    fn add_controls<'a>(&self, t: KaoTheme) -> Element<'a, Message> {
        row![
            text_input("add a name you own, e.g. vitalik.eth", &self.add_input)
                .on_input(Message::AddInputChanged)
                .on_submit(Message::AddName)
                .padding(Padding::from([8, 12]))
                .size(13)
                .style(move |_, s| text_input_style(t, s)),
            Space::new().width(8),
            small_secondary_button(t, if self.adding { "…" } else { "Add" })
                .on_press(Message::AddName),
            Space::new().width(8),
            small_secondary_button(
                t,
                if self.scanning {
                    "Scanning…"
                } else {
                    "↻ Refresh"
                }
            )
            .on_press(Message::Refresh),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill)
        .into()
    }

    fn owned_row<'a>(&self, t: KaoTheme, n: &'a NameStatus, idx: usize) -> Element<'a, Message> {
        let badge = registry_badge(t, &n.registry);
        let title = text(n.full.clone()).size(15).color(t.text).font(bold());

        let (state_txt, state_col) = match n.state() {
            NameState::Active => (
                format!("expires in {}", fmt_days(n.seconds_remaining())),
                t.sub,
            ),
            NameState::Grace => ("in grace — renew now".to_string(), t.down),
            NameState::Permanent => ("permanent · immutable".to_string(), t.sub),
            NameState::Unregistered => ("expired".to_string(), t.down),
        };

        let info = row![badge, Space::new().width(8), title]
            .align_y(Alignment::Center)
            .width(Length::Fill);

        // State (and Manage, for the commit-reveal registrars) sit on the right;
        // the resolved address is intentionally omitted from the list — for XNS
        // it's just the owner again, and it lives in the Manage view for the rest.
        let mut right =
            row![text(state_txt).size(11).color(state_col).font(mono())].align_y(Alignment::Center);
        if n.registry.supports_renew() {
            right = right.push(Space::new().width(12));
            right =
                right.push(small_secondary_button(t, "Manage").on_press(Message::OpenManage(idx)));
        }

        card_row(t, info.into(), right.into())
    }

    fn result_row<'a>(&self, t: KaoTheme, hit: &'a SearchHit, idx: usize) -> Element<'a, Message> {
        let badge = registry_badge(t, &hit.registry);
        let title = text(hit.full.clone()).size(15).color(t.text).font(bold());

        let (kao, kao_col, status_line_el, right): (
            &str,
            Color,
            Element<'_, Message>,
            Element<'_, Message>,
        ) = match &hit.status {
            HitStatus::Available { quote } => {
                let price = match quote {
                    Some(q) if q.total == U256::ZERO => "free".to_string(),
                    Some(q) => format!("≈ {} ETH", fmt_eth(q.total)),
                    None => "price unavailable".to_string(),
                };
                let perm = if hit.registry.is_xns() {
                    " · permanent"
                } else {
                    ""
                };
                (
                    KAO_AVAILABLE,
                    t.up,
                    text(format!("available · {price}{perm}"))
                        .size(11)
                        .color(t.up)
                        .font(mono())
                        .into(),
                    pill_button(t, "Register", Message::PickResult(idx)),
                )
            }
            HitStatus::Taken { owner } => {
                let yours = *owner == Some(self.owner) || self.owns(&hit.registry, &hit.label);
                let label = if yours { "you own this" } else { "taken" };
                let col = if yours { t.a2 } else { t.sub };
                (
                    KAO_TAKEN,
                    t.sub,
                    text(label).size(11).color(col).font(mono()).into(),
                    Space::new().width(0).into(),
                )
            }
            HitStatus::Unavailable { reason } => (
                "·",
                t.sub,
                text(reason.clone())
                    .size(11)
                    .color(t.sub)
                    .font(mono())
                    .into(),
                Space::new().width(0).into(),
            ),
        };

        let info = column![
            row![
                badge,
                Space::new().width(8),
                title,
                Space::new().width(8),
                text(kao).size(13).color(kao_col),
            ]
            .align_y(Alignment::Center),
            Space::new().height(3),
            status_line_el,
        ]
        .width(Length::Fill);

        card_row(t, info.into(), right)
    }

    fn register_view<'a>(&'a self, t: KaoTheme) -> Element<'a, Message> {
        let Some(r) = &self.reg else {
            return self.home_view(t);
        };
        let back = ghost_button(t, text("← Names").size(13).color(t.sub).font(bold()))
            .on_press(Message::Back);

        let header = row![
            registry_badge(t, &r.registry),
            Space::new().width(10),
            text(r.full.clone()).size(20).color(t.text).font(bold()),
        ]
        .align_y(Alignment::Center);

        let mut body = column![
            back,
            Space::new().height(10),
            header,
            Space::new().height(6)
        ]
        .width(Length::Fill)
        .max_width(560);

        // Sub-heading: how this namespace registers.
        let sub = if r.registry.is_commit_reveal() {
            "Two steps: commit, wait ~60s (anti-front-running), then register."
        } else {
            "One transaction. XNS names are permanent, immutable & non-transferable."
        };
        body = body.push(text(sub).size(12).color(t.sub));
        body = body.push(Space::new().height(16));

        // ENS duration stepper (only ENS honours a multi-year term).
        if r.registry == Registry::Ens {
            body = body.push(self.years_stepper(t, r.years));
            body = body.push(Space::new().height(16));
        }

        // XNS one-name-per-address heads-up.
        if r.registry.is_xns() && self.owned.iter().any(|n| n.registry.is_xns()) {
            body = body.push(
                text("Heads up: XNS allows one name per address, and you already hold one.")
                    .size(11)
                    .color(t.down),
            );
            body = body.push(Space::new().height(10));
        }

        body = body.push(self.reg_phase_view(t, r));
        scroll(t, body.into())
    }

    fn reg_phase_view<'a>(&self, t: KaoTheme, r: &'a RegisterFlow) -> Element<'a, Message> {
        match &r.phase {
            RegPhase::Ready { quote } => {
                let total = match quote {
                    Some(q) if q.total == U256::ZERO => "free".to_string(),
                    Some(q) => format!("≈ {} ETH", fmt_eth(q.total)),
                    None => "price unavailable".to_string(),
                };
                let price = if r.quoting {
                    "calculating…".to_string()
                } else {
                    total.clone()
                };
                let btn_label = if r.registry.is_commit_reveal() {
                    "Register — step 1 of 2 (commit)"
                } else {
                    "Register"
                };
                // What the *first* transaction actually moves: the commit step
                // sends nothing (the fee is attached to the step-2 reveal); the
                // XNS one-shot sends the price up front.
                let sends = if r.registry.is_commit_reveal() {
                    "nothing this step — fee is sent at step 2".to_string()
                } else if r.quoting {
                    "calculating…".to_string()
                } else {
                    total
                };
                let review = self.sign_review(t, r.registry.registrar_contract(), sends);
                // Hold the action while a re-quote is in flight so a name can't
                // be committed against a stale price.
                let btn = primary_button(t, btn_label, !r.quoting);
                let btn = if r.quoting {
                    btn
                } else {
                    btn.on_press(Message::StartRegister)
                };
                column![
                    text(price).size(18).color(t.text).font(bold()),
                    Space::new().height(4),
                    text("plus network gas · excess is refunded on-chain")
                        .size(11)
                        .color(t.sub),
                    Space::new().height(16),
                    review,
                    Space::new().height(16),
                    btn,
                ]
                .into()
            }
            RegPhase::Committing => status_line(t, "Committing… confirm on your device.", t.sub),
            RegPhase::Waiting { since, .. } => {
                let elapsed = crate::names::manage::now_secs().saturating_sub(*since);
                if elapsed > registrar::MAX_COMMITMENT_AGE {
                    return column![
                        status_line(t, "Commitment expired (waited over 24h).", t.down),
                        Space::new().height(10),
                        secondary_button(t, "Start over").on_press(Message::ResetRegister),
                    ]
                    .into();
                }
                let remaining = registrar::MIN_COMMITMENT_AGE.saturating_sub(elapsed);
                if remaining > 0 {
                    column![
                        status_line(
                            t,
                            &format!("Commit confirmed. Waiting {remaining}s before step 2…"),
                            t.sub,
                        ),
                        Space::new().height(6),
                        text("This pause stops anyone front-running your registration.")
                            .size(11)
                            .color(t.sub),
                    ]
                    .into()
                } else {
                    column![
                        status_line(t, "Ready to finish.", t.up),
                        Space::new().height(10),
                        self.sign_review(
                            t,
                            r.registry.registrar_contract(),
                            "the registration fee (excess refunded)".to_string(),
                        ),
                        Space::new().height(12),
                        primary_button(t, "Complete registration — step 2 of 2", true)
                            .on_press(Message::CompleteRegister),
                    ]
                    .into()
                }
            }
            RegPhase::Registering => status_line(t, "Registering… confirm on your device.", t.sub),
            RegPhase::Done => column![
                status_line(t, &format!("Registered {} {KAO_AVAILABLE}", r.full), t.up),
                Space::new().height(12),
                primary_button(t, "Back to my names", true).on_press(Message::Back),
            ]
            .into(),
            RegPhase::Failed(e) => column![
                status_line(t, e, t.down),
                Space::new().height(10),
                secondary_button(t, "Back").on_press(Message::ResetRegister),
            ]
            .into(),
        }
    }

    /// A compact "what you'll sign" preview shown before each on-chain step.
    /// Continuing opens the full clear-signing review (the decoded call, args and
    /// value); this card is just an at-a-glance summary of the destination
    /// contract and the ETH the step moves.
    fn sign_review<'a>(
        &self,
        t: KaoTheme,
        contract: Address,
        sends: String,
    ) -> Element<'a, Message> {
        let label_w = Length::Fixed(64.0);
        column![
            text("You'll sign — full details on the next screen")
                .size(11)
                .color(t.sub),
            Space::new().height(8),
            row![
                text("Contract").size(12).color(t.sub).width(label_w),
                colored_address(t, contract),
            ]
            .align_y(Alignment::Center),
            Space::new().height(4),
            row![
                text("Sends").size(12).color(t.sub).width(label_w),
                text(sends).size(12).color(t.text).font(mono()),
            ]
            .align_y(Alignment::Center),
            Space::new().height(8),
            text(
                "Continue to review the full decoded transaction before signing. \
                 A hardware wallet still shows a hash to approve — the decode is shown here."
            )
            .size(10)
            .color(t.sub),
        ]
        .padding(Padding::from([12, 14]))
        .width(Length::Fill)
        .into()
    }

    fn years_stepper<'a>(&self, t: KaoTheme, years: u32) -> Element<'a, Message> {
        row![
            text("Duration").size(13).color(t.sub),
            Space::new().width(Length::Fill),
            stepper_button(t, "−", Message::YearsDec),
            Space::new().width(10),
            text(format!(
                "{} year{}",
                years,
                if years == 1 { "" } else { "s" }
            ))
            .size(14)
            .color(t.text)
            .font(bold()),
            Space::new().width(10),
            stepper_button(t, "+", Message::YearsInc),
        ]
        .align_y(Alignment::Center)
        .width(Length::Fill)
        .into()
    }

    fn manage_view<'a>(&'a self, t: KaoTheme, idx: usize) -> Element<'a, Message> {
        let Some(n) = self.owned.get(idx) else {
            return self.home_view(t);
        };
        let back = ghost_button(t, text("← Names").size(13).color(t.sub).font(bold()))
            .on_press(Message::Back);

        let header = row![
            registry_badge(t, &n.registry),
            Space::new().width(10),
            text(n.full.clone()).size(20).color(t.text).font(bold()),
        ]
        .align_y(Alignment::Center);

        let (state_txt, state_col) = match n.state() {
            NameState::Active => (
                format!("Expires in {}", fmt_days(n.seconds_remaining())),
                t.sub,
            ),
            NameState::Grace => ("In grace period — renew now or lose it".to_string(), t.down),
            NameState::Permanent => ("Permanent · immutable".to_string(), t.sub),
            NameState::Unregistered => ("Expired".to_string(), t.down),
        };

        let mut body = column![
            back,
            Space::new().height(10),
            header,
            Space::new().height(6),
            text(state_txt).size(12).color(state_col).font(mono()),
            Space::new().height(18),
        ]
        .width(Length::Fill)
        .max_width(560);

        // ── Renew ──
        let renew_stepper = if n.registry == Registry::Ens {
            row![
                text("Add").size(13).color(t.sub),
                Space::new().width(Length::Fill),
                stepper_button(t, "−", Message::RenewYearsDec),
                Space::new().width(10),
                text(format!(
                    "{} year{}",
                    self.manage_years,
                    if self.manage_years == 1 { "" } else { "s" }
                ))
                .size(14)
                .color(t.text)
                .font(bold()),
                Space::new().width(10),
                stepper_button(t, "+", Message::RenewYearsInc),
            ]
            .align_y(Alignment::Center)
            .width(Length::Fill)
        } else {
            row![
                text("Renewal adds a fixed 1-year term")
                    .size(12)
                    .color(t.sub)
            ]
        };

        let renew_btn = primary_button(
            t,
            if self.manage_busy {
                "Working…"
            } else {
                "Renew"
            },
            true,
        )
        .on_press(Message::Renew);

        body = body.push(card(
            t,
            column![
                text("Prolong").size(13).color(t.text).font(bold()),
                Space::new().height(10),
                renew_stepper,
                Space::new().height(12),
                renew_btn,
            ]
            .into(),
        ));
        body = body.push(Space::new().height(14));

        // ── Set recipient ──
        let current = match n.recipient {
            Some(a) => row![text("now → ").size(11).color(t.sub), colored_address(t, a)]
                .align_y(Alignment::Center),
            None => row![text("no address record yet").size(11).color(t.sub)],
        };
        body = body.push(card(
            t,
            column![
                text("Set recipient").size(13).color(t.text).font(bold()),
                Space::new().height(4),
                text("the address this name resolves to (can differ from the owner)")
                    .size(11)
                    .color(t.sub),
                Space::new().height(8),
                current,
                Space::new().height(10),
                text_input("0x… recipient address", &self.manage_recipient)
                    .on_input(Message::ManageRecipientChanged)
                    .on_submit(Message::SetRecipient)
                    .padding(Padding::from([8, 12]))
                    .size(13)
                    .style(move |_, s| text_input_style(t, s)),
                Space::new().height(10),
                secondary_button(t, "Update recipient").on_press(Message::SetRecipient),
            ]
            .into(),
        ));

        if let Some((is_err, msg)) = &self.manage_notice {
            body = body.push(Space::new().height(12));
            body = body.push(
                text(msg.clone())
                    .size(12)
                    .color(if *is_err { t.down } else { t.up }),
            );
        }

        scroll(t, body.into())
    }
}

// ── small view helpers ──────────────────────────────────────────────────────

fn scroll<'a>(t: KaoTheme, content: Element<'a, Message>) -> Element<'a, Message> {
    iced::widget::scrollable(
        container(content)
            .center_x(Length::Fill)
            .padding(Padding::from([28, 32])),
    )
    .width(Length::Fill)
    .height(Length::Fill)
    .style(move |_, s| crate::ui::kao_widgets::kao_scrollable_style(t, s))
    .into()
}

fn section_label<'a>(t: KaoTheme, label: &'a str) -> Element<'a, Message> {
    text(label)
        .size(11)
        .color(t.sub)
        .font(crate::ui::kao_widgets::mono_bold())
        .into()
}

fn empty_hint<'a>(t: KaoTheme, msg: &'a str) -> Element<'a, Message> {
    container(text(msg).size(12).color(t.sub))
        .padding(Padding::from([14, 4]))
        .into()
}

/// A standard card with `info` on the left (filling) and `right` aligned at the
/// end.
fn card_row<'a>(
    t: KaoTheme,
    info: Element<'a, Message>,
    right: Element<'a, Message>,
) -> Element<'a, Message> {
    container(
        row![info, right]
            .align_y(Alignment::Center)
            .width(Length::Fill),
    )
    .padding(Padding::from([12, 14]))
    .width(Length::Fill)
    .style(move |_| container::Style {
        background: Some(Background::Color(t.card_alt)),
        border: Border {
            color: t.border,
            width: 1.0,
            radius: Radius::from(12),
        },
        text_color: Some(t.text),
        ..container::Style::default()
    })
    .into()
}

fn card<'a>(t: KaoTheme, inner: Element<'a, Message>) -> Element<'a, Message> {
    container(inner)
        .padding(Padding::from([14, 16]))
        .width(Length::Fill)
        .style(move |_| container::Style {
            background: Some(Background::Color(t.card)),
            border: Border {
                color: t.border,
                width: 1.0,
                radius: Radius::from(14),
            },
            text_color: Some(t.text),
            ..container::Style::default()
        })
        .into()
}

fn status_line<'a>(t: KaoTheme, msg: &str, color: iced::Color) -> Element<'a, Message> {
    let _ = t;
    text(msg.to_string()).size(13).color(color).into()
}

/// A compact accent CTA — the small, content-sized counterpart to the
/// full-width `primary_button`, for inline row actions (Search, Register).
fn pill_button<'a>(t: KaoTheme, label: &'a str, msg: Message) -> Element<'a, Message> {
    button(
        text(label.to_string())
            .size(13)
            .color(Color::WHITE)
            .font(bold()),
    )
    .padding(Padding::from([9, 18]))
    .on_press(msg)
    .style(move |_, status| button::Style {
        background: Some(Background::Color(match status {
            button::Status::Hovered | button::Status::Pressed => with_alpha(t.a1, 0.82),
            _ => t.a1,
        })),
        text_color: Color::WHITE,
        border: Border {
            color: Color::TRANSPARENT,
            width: 0.0,
            radius: Radius::from(10),
        },
        ..button::Style::default()
    })
    .into()
}

fn stepper_button<'a>(t: KaoTheme, glyph: &'a str, msg: Message) -> Element<'a, Message> {
    button(text(glyph).size(16).color(t.text).font(bold()))
        .padding(Padding::from([2, 12]))
        .on_press(msg)
        .style(move |_, status| button::Style {
            background: Some(Background::Color(match status {
                button::Status::Hovered | button::Status::Pressed => with_alpha(t.a1, 0.16),
                _ => t.card_alt,
            })),
            text_color: t.text,
            border: Border {
                color: t.border,
                width: 1.0,
                radius: Radius::from(8),
            },
            ..button::Style::default()
        })
        .into()
}

/// Accent per registry: ENS → a1, GNS → a2, WNS → a3, XNS → up (a distinct hue).
fn registry_accent(t: KaoTheme, r: &Registry) -> Color {
    match r {
        Registry::Ens => t.a1,
        Registry::Gns => t.a2,
        Registry::Wns => t.a3,
        Registry::Xns { .. } => t.up,
    }
}

fn registry_badge<'a>(t: KaoTheme, r: &Registry) -> Element<'a, Message> {
    let accent = registry_accent(t, r);
    container(
        text(r.badge().to_string())
            .size(10)
            .color(accent)
            .font(bold()),
    )
    .padding(Padding::from([2, 7]))
    .style(move |_| container::Style {
        background: Some(Background::Color(with_alpha(accent, 0.12))),
        border: Border {
            color: with_alpha(accent, 0.3),
            width: 1.0,
            radius: Radius::from(6),
        },
        ..container::Style::default()
    })
    .into()
}

/// Format wei as a short ETH string (up to 5 dp, trailing zeros trimmed).
fn fmt_eth(wei: U256) -> String {
    let s = alloy::primitives::utils::format_ether(wei);
    match s.parse::<f64>() {
        Ok(v) => {
            let formatted = format!("{v:.5}");
            formatted
                .trim_end_matches('0')
                .trim_end_matches('.')
                .to_string()
        }
        Err(_) => s,
    }
}

/// "340 days" / "1 day" / "12 hours" for a remaining-seconds count.
fn fmt_days(secs: u64) -> String {
    let days = secs / 86_400;
    if days >= 1 {
        format!("{days} day{}", if days == 1 { "" } else { "s" })
    } else {
        let hrs = secs / 3_600;
        format!("{hrs} hour{}", if hrs == 1 { "" } else { "s" })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::address;

    fn app() -> NamesApp {
        NamesApp::new(address!("0x000000000000000000000000000000000000bEEF"))
    }

    fn owned_status(registry: Registry, label: &str, owner: Address) -> NameStatus {
        let full = registry.full_name(label);
        NameStatus {
            registry,
            label: label.to_string(),
            full,
            expires_at: Some(crate::names::manage::now_secs() + registrar::YEAR_SECONDS),
            now: crate::names::manage::now_secs(),
            owner: Some(owner),
            recipient: Some(owner),
        }
    }

    #[test]
    fn on_open_kicks_off_one_reverse_scan() {
        let mut a = app();
        assert!(matches!(a.on_open(), Some(Outcome::ReverseScan)));
        assert!(a.scanning);
        // Only once.
        assert!(a.on_open().is_none());
    }

    #[test]
    fn bare_query_searches_all_default_namespaces() {
        let mut a = app();
        a.update(Message::QueryChanged("rat".into()));
        let out = a.update(Message::Search);
        match out {
            Some(Outcome::Search {
                label, registries, ..
            }) => {
                assert_eq!(label, "rat");
                assert_eq!(registries.len(), 5);
            }
            _ => panic!("expected Search, got {out:?}"),
        }
        assert!(a.searching);
    }

    #[test]
    fn explicit_xns_query_searches_one_namespace() {
        let mut a = app();
        a.update(Message::QueryChanged("cow.cheese".into()));
        let out = a.update(Message::Search);
        match out {
            Some(Outcome::Search {
                label, registries, ..
            }) => {
                assert_eq!(label, "cow");
                assert_eq!(
                    registries,
                    vec![Registry::Xns {
                        namespace: "cheese".to_string()
                    }]
                );
            }
            _ => panic!("expected Search, got {out:?}"),
        }
    }

    #[test]
    fn pick_available_result_opens_register_panel() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Xns {
                namespace: "crops".to_string(),
            },
            label: "cow".to_string(),
            full: "cow.crops".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        assert_eq!(a.view, View::Register);
        // XNS register is a single step → StartRegister emits RegisterXns. The
        // pane stays in Ready until the clear-signing review is confirmed (the
        // coordinator then calls `begin_reveal`); a cancel leaves it untouched.
        let out = a.update(Message::StartRegister);
        match out {
            Some(Outcome::RegisterXns { namespace, label }) => {
                assert_eq!(namespace, "crops");
                assert_eq!(label, "cow");
            }
            _ => panic!("expected RegisterXns, got {out:?}"),
        }
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Ready { .. }
        ));
        // Confirming the review flips the pane into the broadcast phase.
        a.begin_reveal();
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Registering
        ));
    }

    #[test]
    fn ens_duration_change_requotes_and_drops_stale_results() {
        let mut a = app();
        let one_year = crate::names::manage::RegisterQuote {
            base: U256::from(100u64),
            premium: U256::ZERO,
            total: U256::from(100u64),
            duration_secs: registrar::YEAR_SECONDS,
        };
        a.results = vec![SearchHit {
            registry: Registry::Ens,
            label: "vitalik".to_string(),
            full: "vitalik.eth".to_string(),
            status: HitStatus::Available {
                quote: Some(one_year),
            },
        }];
        a.update(Message::PickResult(0));
        assert_eq!(a.reg.as_ref().unwrap().years, 1);

        // Bumping the term re-quotes for the new duration and marks the panel busy.
        let out = a.update(Message::YearsInc);
        match out {
            Some(Outcome::Quote {
                namespace,
                label,
                years,
            }) => {
                assert_eq!(namespace, Namespace::Ens);
                assert_eq!(label, "vitalik");
                assert_eq!(years, 2);
            }
            _ => panic!("expected Quote, got {out:?}"),
        }
        assert!(a.reg.as_ref().unwrap().quoting);

        // A result for the *current* term lands → price refreshes, busy clears.
        let two_year = crate::names::manage::RegisterQuote {
            base: U256::from(200u64),
            premium: U256::ZERO,
            total: U256::from(200u64),
            duration_secs: registrar::ens_duration_secs(2),
        };
        a.on_quote(2, Ok(two_year));
        assert!(!a.reg.as_ref().unwrap().quoting);
        match &a.reg.as_ref().unwrap().phase {
            RegPhase::Ready { quote: Some(q) } => assert_eq!(q.total, U256::from(200u64)),
            other => panic!("expected refreshed Ready quote, got {other:?}"),
        }

        // A late result for a superseded term (years == 1) is ignored.
        let stale = crate::names::manage::RegisterQuote {
            base: U256::from(100u64),
            premium: U256::ZERO,
            total: U256::from(100u64),
            duration_secs: registrar::YEAR_SECONDS,
        };
        a.on_quote(1, Ok(stale));
        match &a.reg.as_ref().unwrap().phase {
            RegPhase::Ready { quote: Some(q) } => {
                assert_eq!(q.total, U256::from(200u64), "stale re-quote must not win")
            }
            other => panic!("expected Ready quote, got {other:?}"),
        }

        // Clamped at the lower bound: a no-op step doesn't spawn a read.
        a.update(Message::YearsDec); // 2 -> 1
        let out = a.update(Message::YearsDec); // already at MIN_YEARS
        assert!(out.is_none(), "no re-quote when the term didn't change");
    }

    #[test]
    fn non_ens_duration_change_does_not_requote() {
        // GNS grants a fixed term and has no stepper, so a stray YearsInc must
        // not emit a read.
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Gns,
            label: "apoorv".to_string(),
            full: "apoorv.gwei".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        assert!(a.update(Message::YearsInc).is_none());
        assert!(!a.reg.as_ref().unwrap().quoting);
    }

    #[test]
    fn pick_taken_result_does_nothing() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Ens,
            label: "vitalik".to_string(),
            full: "vitalik.eth".to_string(),
            status: HitStatus::Taken { owner: None },
        }];
        a.update(Message::PickResult(0));
        assert_eq!(a.view, View::Home, "taken names aren't registerable");
        assert!(a.reg.is_none());
    }

    #[test]
    fn legacy_register_runs_commit_then_reveal() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Gns,
            label: "apoorv".to_string(),
            full: "apoorv.gwei".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        // Step 1: commit. The pane emits Commit but stays Ready until the
        // clear-signing review is confirmed (coordinator calls `begin_commit`).
        let out = a.update(Message::StartRegister);
        assert!(matches!(out, Some(Outcome::Commit { .. })));
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Ready { .. }
        ));
        a.begin_commit();
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Committing
        ));
        // Coordinator reports commit mined → Waiting.
        let plan = RegisterPlan {
            namespace: Namespace::Gns,
            label: "apoorv".into(),
            owner: a.owner,
            duration_secs: registrar::YEAR_SECONDS,
            secret: alloy::primitives::B256::repeat_byte(7),
        };
        a.on_commit(Ok((plan, TxHash::ZERO)));
        // Too early → no reveal.
        assert!(a.update(Message::CompleteRegister).is_none());
        // Backdate past the 60s window → reveal allowed.
        if let Some(RegisterFlow {
            phase: RegPhase::Waiting { since, .. },
            ..
        }) = &mut a.reg
        {
            *since = crate::names::manage::now_secs() - registrar::MIN_COMMITMENT_AGE - 1;
        }
        // Step 2: reveal. Again, emits the outcome but stays Waiting until the
        // review is confirmed.
        let out = a.update(Message::CompleteRegister);
        assert!(matches!(out, Some(Outcome::Register { .. })));
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Waiting { .. }
        ));
        a.begin_reveal();
        assert!(matches!(
            a.reg.as_ref().unwrap().phase,
            RegPhase::Registering
        ));
    }

    #[test]
    fn complete_register_blocked_after_max_commitment_age() {
        let mut a = app();
        a.reg = Some(RegisterFlow {
            registry: Registry::Gns,
            label: "apoorv".into(),
            full: "apoorv.gwei".into(),
            years: 1,
            quoting: false,
            phase: RegPhase::Waiting {
                plan: RegisterPlan {
                    namespace: Namespace::Gns,
                    label: "apoorv".into(),
                    owner: a.owner,
                    duration_secs: registrar::YEAR_SECONDS,
                    secret: alloy::primitives::B256::repeat_byte(7),
                },
                since: crate::names::manage::now_secs()
                    .saturating_sub(registrar::MAX_COMMITMENT_AGE + 1),
            },
        });
        assert!(a.update(Message::CompleteRegister).is_none());
        assert!(matches!(a.reg.as_ref().unwrap().phase, RegPhase::Failed(_)));
    }

    #[test]
    fn add_name_rejects_bare_label() {
        let mut a = app();
        a.update(Message::AddInputChanged("rat".into()));
        assert!(a.update(Message::AddName).is_none());
        assert!(a.notice.as_ref().unwrap().0, "notice is an error");
    }

    #[test]
    fn on_status_only_keeps_owned_names() {
        let mut a = app();
        a.on_status(Ok(owned_status(Registry::Gns, "apoorv", a.owner)));
        assert_eq!(a.owned.len(), 1);
        a.on_status(Ok(owned_status(
            Registry::Ens,
            "vitalik",
            address!("0x00000000000000000000000000000000DeaDBeef"),
        )));
        assert_eq!(a.owned.len(), 1, "not-owned name must not be added");
        assert!(a.notice.as_ref().unwrap().0);
    }

    #[test]
    fn xns_owned_name_has_no_manage() {
        // OpenManage on an XNS row is a no-op (nothing to renew/re-point).
        let mut a = app();
        let mut s = owned_status(
            Registry::Xns {
                namespace: "xns".to_string(),
            },
            "alice",
            a.owner,
        );
        s.expires_at = None;
        a.owned.push(s);
        a.update(Message::OpenManage(0));
        assert_eq!(a.view, View::Home, "XNS has no manage view");
    }

    #[test]
    fn manage_set_recipient_validates_address() {
        let mut a = app();
        a.on_status(Ok(owned_status(Registry::Gns, "apoorv", a.owner)));
        a.update(Message::OpenManage(0));
        assert_eq!(a.view, View::Manage(0));
        a.update(Message::ManageRecipientChanged("nope".into()));
        assert!(a.update(Message::SetRecipient).is_none());
        assert!(a.manage_notice.as_ref().unwrap().0);
        a.update(Message::ManageRecipientChanged(
            "0x00000000000000000000000000000000DeaDBeef".into(),
        ));
        let out = a.update(Message::SetRecipient);
        assert!(matches!(out, Some(Outcome::SetRecipient { .. })));
        // The card stays idle until the clear-signing review is confirmed; the
        // coordinator then calls `begin_manage`.
        assert!(!a.manage_busy);
        a.begin_manage();
        assert!(a.manage_busy);
    }

    #[test]
    fn editing_query_clears_stale_results_immediately() {
        let mut a = app();
        // A prior search's rows are sitting in the pane.
        a.results = vec![SearchHit {
            registry: Registry::Ens,
            label: "old".to_string(),
            full: "old.eth".to_string(),
            status: HitStatus::Taken { owner: None },
        }];
        // Typing a single char drops them at once (no waiting for Enter) and
        // schedules an auto-search — so the old rows never show under new text.
        a.update(Message::QueryChanged("new".into()));
        assert!(a.results.is_empty(), "stale rows cleared on edit");
        assert!(!a.searching);
        assert!(a.pending_search, "auto-search scheduled");

        // Pressing Search (or Enter) fires immediately and cancels the debounce.
        let out = a.update(Message::Search);
        assert!(matches!(out, Some(Outcome::Search { .. })));
        assert!(a.searching);
        assert!(!a.pending_search, "manual search consumes the debounce");
    }

    #[test]
    fn clearing_the_box_leaves_search_mode() {
        let mut a = app();
        a.update(Message::QueryChanged("kitty".into()));
        assert!(a.pending_search);
        a.update(Message::QueryChanged("   ".into())); // whitespace-only ⇒ empty
        assert!(!a.pending_search, "no auto-search for an empty box");
        assert!(a.results.is_empty());
    }

    #[test]
    fn auto_search_fires_after_typing_settles() {
        let mut a = app();
        a.update(Message::QueryChanged("kitty".into()));
        assert!(a.pending_search);
        // One quiet tick isn't enough — the debounce needs the full settle window.
        assert!(a.update(Message::DebounceTick).is_none());
        assert!(a.pending_search);
        // The threshold tick fires the search on its own.
        match a.update(Message::DebounceTick) {
            Some(Outcome::Search { label, .. }) => assert_eq!(label, "kitty"),
            other => panic!("expected auto Search, got {other:?}"),
        }
        assert!(!a.pending_search, "debounce consumed");
        assert!(a.searching);
    }

    #[test]
    fn typing_resets_the_debounce() {
        let mut a = app();
        a.update(Message::QueryChanged("ki".into()));
        a.update(Message::DebounceTick); // idle_ticks = 1
        a.update(Message::QueryChanged("kit".into())); // a keystroke resets it
        assert!(
            a.update(Message::DebounceTick).is_none(),
            "reset — needs another full quiet window"
        );
        assert!(matches!(
            a.update(Message::DebounceTick),
            Some(Outcome::Search { .. })
        ));
    }

    #[test]
    fn auto_search_waits_on_unparseable_query() {
        let mut a = app();
        a.update(Message::QueryChanged("cow.".into())); // half-typed ⇒ parse error
        a.update(Message::DebounceTick);
        let out = a.update(Message::DebounceTick);
        assert!(out.is_none(), "incomplete query doesn't auto-fire");
        assert!(!a.pending_search, "debounce consumed");
        assert!(a.notice.is_none(), "no parse error flashed mid-typing");
    }

    #[test]
    fn stale_search_reply_is_dropped() {
        let mut a = app();
        // First search is in flight (seq 1).
        a.update(Message::QueryChanged("aaa".into()));
        let seq1 = match a.update(Message::Search) {
            Some(Outcome::Search { seq, .. }) => seq,
            other => panic!("expected Search, got {other:?}"),
        };
        // User retypes and searches again before the first lands (seq 2).
        a.update(Message::QueryChanged("bbb".into()));
        let seq2 = match a.update(Message::Search) {
            Some(Outcome::Search { seq, .. }) => seq,
            other => panic!("expected Search, got {other:?}"),
        };
        assert_ne!(seq1, seq2);

        // The slow first reply now arrives — it must be ignored: results stay
        // empty and the spinner keeps spinning for the in-flight second search.
        a.on_search(
            seq1,
            Ok(vec![SearchHit {
                registry: Registry::Ens,
                label: "aaa".to_string(),
                full: "aaa.eth".to_string(),
                status: HitStatus::Taken { owner: None },
            }]),
        );
        assert!(a.results.is_empty(), "stale reply must not paint");
        assert!(a.searching, "still waiting on the current search");

        // The current reply lands and is applied.
        a.on_search(
            seq2,
            Ok(vec![SearchHit {
                registry: Registry::Ens,
                label: "bbb".to_string(),
                full: "bbb.eth".to_string(),
                status: HitStatus::Available { quote: None },
            }]),
        );
        assert!(!a.searching);
        assert_eq!(a.results.len(), 1);
        assert_eq!(a.results[0].full, "bbb.eth");
    }

    #[test]
    fn register_success_marks_row_owned_and_lists_it() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Xns {
                namespace: "crops".to_string(),
            },
            label: "cow".to_string(),
            full: "cow.crops".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0));
        a.update(Message::StartRegister); // XNS one-shot → Registering
        a.on_register(Ok(("cow.crops".to_string(), TxHash::ZERO)));

        assert!(matches!(a.reg.as_ref().unwrap().phase, RegPhase::Done));
        // The search row no longer offers Register — it reads as ours now.
        match &a.results[0].status {
            HitStatus::Taken { owner } => assert_eq!(*owner, Some(a.owner)),
            other => panic!("expected Taken-by-us, got {other:?}"),
        }
        // …and it appears under "Your names" (permanent XNS → no expiry).
        assert_eq!(a.owned.len(), 1);
        assert_eq!(a.owned[0].full, "cow.crops");
        assert!(a.owned[0].owned_by(a.owner));
        assert_eq!(a.owned[0].expires_at, None);
        assert_eq!(a.owned[0].state(), NameState::Permanent);
    }

    #[test]
    fn legacy_register_success_records_term_expiry() {
        let mut a = app();
        a.results = vec![SearchHit {
            registry: Registry::Ens,
            label: "vitalik".to_string(),
            full: "vitalik.eth".to_string(),
            status: HitStatus::Available { quote: None },
        }];
        a.update(Message::PickResult(0)); // years defaults to 1
        a.on_register(Ok(("vitalik.eth".to_string(), TxHash::ZERO)));
        // A commit-reveal name lands in the owned list with a future expiry.
        assert_eq!(a.owned.len(), 1);
        let exp = a.owned[0]
            .expires_at
            .expect("commit-reveal name carries an expiry");
        assert!(exp > crate::names::manage::now_secs());
        assert_eq!(a.owned[0].state(), NameState::Active);
    }
}
